USE [BusinessCenter]
GO

/****** Object:  Table [dbo].[DCBC_ENTITY_CORP]    Script Date: 05/09/2015 19:04:37 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[DCBC_ENTITY_CORP](
	[DCBC_ENTITY_ID] [int] IDENTITY(30000000,1) NOT NULL,
	[REC_STATUS] [bit] NOT NULL,
	[LAST_UPDATE] [datetime] NOT NULL,
	[DCBC_ENTITY_SOURCE] [varchar](50) NOT NULL
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[DCBC_ENTITY_CORP] ADD  CONSTRAINT [DF_DCBC_ENTITY_CORP_REC_STATUS]  DEFAULT ((1)) FOR [REC_STATUS]
GO

ALTER TABLE [dbo].[DCBC_ENTITY_CORP] ADD  CONSTRAINT [DF_DCBC_ENTITY_CORP_LAST_UPDATE]  DEFAULT (getdate()) FOR [LAST_UPDATE]
GO


