USE [BusinessCenter]
GO

/****** Object:  Table [dbo].[DCBC_ENTITY_OPLA]    Script Date: 05/09/2015 19:05:51 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[DCBC_ENTITY_OPLA](
	[DCBC_ENTITY_ID] [int] IDENTITY(50000000,1) NOT NULL,
	[REC_STATUS] [bit] NOT NULL,
	[LAST_UPDATE] [datetime] NOT NULL,
	[DCBC_ENTITY_SOURCE] [varchar](50) NOT NULL,
	[BOARD_ABBREVIATION] [varchar](10) NULL,
	[LICENSE_PREFIX] [varchar](10) NULL,
	[LICENSE_NUMBER] [varchar](15) NULL,
	[LICENSE_ISSUE_DATE] [date] NULL,
	[LICENSE_EXPIRATION_DATE] [date] NULL,
	[LICENSE_STATUS_CODE] [varchar](1) NULL,
	[FIRST_NAME] [varchar](50) NULL,
	[MIDDLE_NAME] [varchar](50) NULL,
	[LAST_NAME] [varchar](50) NULL,
	[SUFFIX] [varchar](50) NULL,
	[BUSINESS_ADDRESS] [varchar](200) NULL,
	[BUSINESS_CITY] [varchar](50) NULL,
	[BUSINESS_STATE] [varchar](30) NULL,
	[BUSINESS_ZIP] [varchar](30) NULL,
	[BUSINESS_PHONE] [varchar](30) NULL,
	[HOME_ADDRESS] [varchar](200) NULL,
	[HOME_CITY] [varchar](50) NULL,
	[HOME_STATE] [varchar](30) NULL,
	[HOME_ZIP] [varchar](30) NULL,
	[HOME_PHONE] [varchar](30) NULL,
	[EMPLOYER_LICENSE_PREFIX] [varchar](10) NULL,
	[EMPLOYER_LICENSE_PREFIX1] [varchar](10) NULL,
	[EMPLOYER_LICENSE_NUMBER] [varchar](50) NULL,
	[EMPLOYER_NAME] [varchar](200) NULL,
	[EMPLOYER_LICENSE_ISSUE_DATE] [date] NULL,
	[EMPLOYER_LICENSE_EXPIRATION_DATE] [date] NULL,
	[EMPLOYER_LICENSE_STATUS_CODE] [varchar](10) NULL,
	[EMPLOYER_ADDRESS] [varchar](200) NULL,
	[EMPLOYER_CITY] [varchar](50) NULL,
	[EMPLOYER_STATE] [varchar](30) NULL,
	[EMPLOYER_ZIP] [varchar](30) NULL,
	[EMPLOYER_PHONE] [varchar](30) NULL,
	[FULL_NAME] [varchar](200) NULL
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[DCBC_ENTITY_OPLA] ADD  CONSTRAINT [DF_DCBC_ENTITY_OPLA_REC_STATUS]  DEFAULT ((1)) FOR [REC_STATUS]
GO

ALTER TABLE [dbo].[DCBC_ENTITY_OPLA] ADD  CONSTRAINT [DF_DCBC_ENTITY_OPLA_LAST_UPDATE]  DEFAULT (getdate()) FOR [LAST_UPDATE]
GO


