GO
CREATE TABLE [dbo].[MasterState](
	[StateCode] [nvarchar](10) NOT NULL,
	[StateName] [nvarchar](255) NULL,
	[CountryCode] [nvarchar](10) NULL,
 CONSTRAINT [PK_MasterState] PRIMARY KEY CLUSTERED 
(
	[StateCode] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
