using System.Collections.Generic;
using BusinessCenter.Data;
using System;

namespace BusinessCenter.Tests.Setup
{
    public class BblRepositoryData
    {
        private readonly List<DCBC_ENTITY_BBL> _entities;
        public bool IsInitialized;
        public void AddDcbcEntity_Bbl(DCBC_ENTITY_BBL obj)
        {
            _entities.Add(obj);
        }

        public List<DCBC_ENTITY_BBL> BblEntitiesList
        {
            get { return _entities; }
        }

        public BblRepositoryData()
        {
            IsInitialized = true;
            _entities = new List<DCBC_ENTITY_BBL>();

            AddDcbcEntity_Bbl(new DCBC_ENTITY_BBL()
            {

                DCBC_ENTITY_ID = 1,
                REC_STATUS = true,
                LAST_UPDATE = Convert.ToDateTime("2016-01-25 07:26:13.153"),
                DCBC_ENTITY_SOURCE = "BBL",
                SERV_PROV_CODE = "DC",
                B1_PER_ID1 = "15LIC",
                B1_PER_ID2 = "00000",
                B1_PER_ID3 = "22557",
                B1_PER_GROUP = "Licenses",
                B1_PER_TYPE = "Business License",
                B1_PER_SUB_TYPE = "Public Health Food Establish",
                B1_PER_CATEGORY = "Auctioneer",
                B1_APPL_STATUS_ORIGINAL = "Approved",
                B1_APPL_STATUS = "Active",
                B1_ALT_ID = "931315000136",
                APPLICATION_CAP = "931315000139",
                B1_APPL_STATUS_DATE = "Apr 13 201",
                ISSUED_DATE = null,
                B1_HSE_NBR_START = 1215,
                B1_HSE_NBR_END = null,
                B1_HSE_FRAC_NBR_START = null,
                B1_HSE_FRAC_NBR_END = null,
                B1_UNIT_START = null,
                B1_STR_NAME = "CONNECTICUT",
                B1_STR_SUFFIX = "AVE",
                B1_STR_SUFFIX_DIR = "NW",
                B1_SITUS_CITY = "WASHINGTON",
                B1_SITUS_STATE = "DC",
                B1_SITUS_ZIP = "20036",
                FULL_ADDRESS = "1215 CONNECTICUT AVE NW",
                B1_APP_TYPE_ALIAS = "Restaurant",
                SSL = "0159    0075",
                REC_FUL_NAM = "BPERRY",
                Contact_Business_Name = "IMA PIZZA STORE 13 LLC.",
                Contact_FirstName = "NA",
                Contact_MiddleName = null,
                Contact_LastName = "NA",
                Billing_Address1 = "229 1/2 PENNSYLVANIA AVENUE S.E.",
                Billing_Address2 = null,
                Billing_Address3 = null,
                Billing_CITY = "WASHINGTON",
                Billing_STATE = "DC",
                Billing_ZIP = "20003",
                OwnrApplicant_BUSINESS_NAME = "IMA PIZZA STORE 13 LLC.",
                OwnrApplicant_FNAME = "NA",
                OwnrApplicant_MNAME = null,
                OwnrApplicant_LNAME = "NA",
                OwnrApplicant_Address1 = "229 1/2 PENNSYLVANIA AVENUE S.E.",
                OwnrApplicant_Address2 = null,
                OwnrApplicant_Address3 = null,
                OwnrApplicant_CITY = "WASHINGTON",
                OwnrApplicant_STATE = "DC",
                OwnrApplicant_ZIP = "20003",
                RegAgent_BUSINESS_NAME = "S AND P REGISTERED AGENTS INC.",
                RegAgent_FNAME = "NA",
                RegAgent_MNAME = null,
                RegAgent_LNAME = "NA",
                RegAgent_Address1 = "1008 PENNSYLVANIA AVENUE S.E.",
                RegAgent_Address2 = null,
                RegAgent_Address3 = null,
                RegAgent_CITY = "WASHINGTON",
                RegAgent_STATE = "DC",
                RegAgent_ZIP = "20003",
                Attr_TRADE_NAME = null,
                Business_Org = "Limited Liability Company",
                Expiration_Date = DateTime.Now.AddDays(-70).ToString("MM/dd/yyyy"),
                License_Issued_Date = "04/13/2015",
                Period_Start_Date = "4/1/2015",
                License_Category = "General Business|Hotel",
                License_Category_Full = "Public Health: Retail Food Establishment - Restaurant",
                TaxNumber = "SSN",
                FEIN_SSN = "578640373",
                APPLICATION_CAP_STATUS = "Approved",
                APPLICATION_CAP_STATUS_DATE = Convert.ToDateTime("2011-10-03 00:00:00.000"),
                REC_DATE = Convert.ToDateTime("2016-01-25 07:26:13.267")

            });

            AddDcbcEntity_Bbl(new DCBC_ENTITY_BBL()
            {
                DCBC_ENTITY_ID = 2,
                REC_STATUS = true,
                LAST_UPDATE = Convert.ToDateTime("2016-01-25 07:26:13.153"),
                DCBC_ENTITY_SOURCE = "BBL",
                SERV_PROV_CODE = "DC",
                B1_PER_ID1 = "15LIC",
                B1_PER_ID2 = "00000",
                B1_PER_ID3 = "22559",
                B1_PER_GROUP = "Licenses",
                B1_PER_TYPE = "Business License",
                B1_PER_SUB_TYPE = "Public Health Food Establish",
                B1_PER_CATEGORY = "Restaurant",
                B1_APPL_STATUS_ORIGINAL = "Approved",
                B1_APPL_STATUS = "Active",
                B1_ALT_ID = "931315000139",
                APPLICATION_CAP = "931315000136",
                B1_APPL_STATUS_DATE = "Apr 13 201",
                ISSUED_DATE = null,
                B1_HSE_NBR_START = 1723,
                B1_HSE_NBR_END = null,
                B1_HSE_FRAC_NBR_START = null,
                B1_HSE_FRAC_NBR_END = null,
                B1_UNIT_START = null,
                B1_STR_NAME = "CONNECTICUT",
                B1_STR_SUFFIX = "AVE",
                B1_STR_SUFFIX_DIR = "NW",
                B1_SITUS_CITY = "WASHINGTON",
                B1_SITUS_STATE = "DC",
                B1_SITUS_ZIP = "20009",
                FULL_ADDRESS = "1723 CONNECTICUT AV NW",
                B1_APP_TYPE_ALIAS = "Restaurant",
                SSL = "0091    0034",
                REC_FUL_NAM = "BPERRY",
                Contact_Business_Name = "SALTY DOG TAVEM",
                Contact_FirstName = "NA",
                Contact_MiddleName = null,
                Contact_LastName = "NA",
                Billing_Address1 = "1723 CONNECTICUT AVENUE N.W.",
                Billing_Address2 = null,
                Billing_Address3 = null,
                Billing_CITY = "WASHINGTON",
                Billing_STATE = "DC",
                Billing_ZIP = "20019",
                OwnrApplicant_BUSINESS_NAME = "1723 DUPONT L.L.C.",
                OwnrApplicant_FNAME = "NA",
                OwnrApplicant_MNAME = null,
                OwnrApplicant_LNAME = "NA",
                OwnrApplicant_Address1 = "1723 CONNECTICUT AVENUE N.W.",
                OwnrApplicant_Address2 = null,
                OwnrApplicant_Address3 = null,
                OwnrApplicant_CITY = "WASHINGTON",
                OwnrApplicant_STATE = "DC",
                OwnrApplicant_ZIP = "20019",
                RegAgent_BUSINESS_NAME = null,
                RegAgent_FNAME = "ALEX",
                RegAgent_MNAME = null,
                RegAgent_LNAME = "PARASKEVAS",
                RegAgent_Address1 = "6520 6th STREET N.W.",
                RegAgent_Address2 = null,
                RegAgent_Address3 = null,
                RegAgent_CITY = "WASHINGTON",
                RegAgent_STATE = "DC",
                RegAgent_ZIP = "20012",
                Attr_TRADE_NAME = "SALTY DOG TAVEM",
                Business_Org = "Limited Liability Company",
               Expiration_Date = DateTime.Now.AddDays(-100).ToString("yyyy/MM/dd"),
                License_Issued_Date = "04/13/2015",
                Period_Start_Date = "4/1/2015",
                License_Category = "Restaurant",
                License_Category_Full = "Public Health: Retail Food Establishment - Restaurant",
                TaxNumber = "FEIN",
                FEIN_SSN = "202810509",
                APPLICATION_CAP_STATUS = "Billed",
                APPLICATION_CAP_STATUS_DATE = Convert.ToDateTime("2011-10-03 00:00:00.000"),
                REC_DATE = Convert.ToDateTime("2016-01-25 07:26:13.267")
            });

            AddDcbcEntity_Bbl(new DCBC_ENTITY_BBL()
            {
                DCBC_ENTITY_ID = 3,
                REC_STATUS = true,
                LAST_UPDATE = Convert.ToDateTime("2016-01-25 07:26:13.153"),
                DCBC_ENTITY_SOURCE = "BBL",
                SERV_PROV_CODE = "DC",
                B1_PER_ID1 = "15LIC",
                B1_PER_ID2 = "00000",
                B1_PER_ID3 = "22559",
                B1_PER_GROUP = "Licenses",
                B1_PER_TYPE = "Business License",
                B1_PER_SUB_TYPE = "Public Health Food Establish",
                B1_PER_CATEGORY = "Restaurant",
                B1_APPL_STATUS_ORIGINAL = "Approved",
                B1_APPL_STATUS = "Expired",
                B1_ALT_ID = "100113000002",
                APPLICATION_CAP = "100113000001",
                B1_APPL_STATUS_DATE = "Apr 13 201",
                ISSUED_DATE = null,
                B1_HSE_NBR_START = 1723,
                B1_HSE_NBR_END = null,
                B1_HSE_FRAC_NBR_START = null,
                B1_HSE_FRAC_NBR_END = null,
                B1_UNIT_START = null,
                B1_STR_NAME = "CONNECTICUT",
                B1_STR_SUFFIX = "AVE",
                B1_STR_SUFFIX_DIR = "NW",
                B1_SITUS_CITY = "WASHINGTON",
                B1_SITUS_STATE = "DC",
                B1_SITUS_ZIP = "20009",
                FULL_ADDRESS = "1723 CONNECTICUT AV NW",
                B1_APP_TYPE_ALIAS = "Restaurant",
                SSL = "0091    0034",
                REC_FUL_NAM = "BPERRY",
                Contact_Business_Name = "SALTY DOG TAVEM",
                Contact_FirstName = "NA",
                Contact_MiddleName = null,
                Contact_LastName = "NA",
                Billing_Address1 = "1723 CONNECTICUT AVENUE N.W.",
                Billing_Address2 = null,
                Billing_Address3 = null,
                Billing_CITY = "WASHINGTON",
                Billing_STATE = "DC",
                Billing_ZIP = "20019",
                OwnrApplicant_BUSINESS_NAME = "1723 DUPONT L.L.C.",
                OwnrApplicant_FNAME = "NA",
                OwnrApplicant_MNAME = null,
                OwnrApplicant_LNAME = "NA",
                OwnrApplicant_Address1 = "1723 CONNECTICUT AVENUE N.W.",
                OwnrApplicant_Address2 = null,
                OwnrApplicant_Address3 = null,
                OwnrApplicant_CITY = "WASHINGTON",
                OwnrApplicant_STATE = "DC",
                OwnrApplicant_ZIP = "20019",
                RegAgent_BUSINESS_NAME = null,
                RegAgent_FNAME = "ALEX",
                RegAgent_MNAME = null,
                RegAgent_LNAME = "PARASKEVAS",
                RegAgent_Address1 = "6520 6th STREET N.W.",
                RegAgent_Address2 = null,
                RegAgent_Address3 = null,
                RegAgent_CITY = "WASHINGTON",
                RegAgent_STATE = "DC",
                RegAgent_ZIP = "20012",
                Attr_TRADE_NAME = "SALTY DOG TAVEM",
                Business_Org = "Limited Liability Company",
                Expiration_Date = DateTime.Now.AddDays(-150).ToString("yyyy/MM/dd"),
                License_Issued_Date = "04/13/2015",
                Period_Start_Date = "4/1/2015",
                License_Category = "Restaurant",
                License_Category_Full = "Public Health: Retail Food Establishment - Restaurant",
                TaxNumber = "SSN",
                FEIN_SSN = "579864686",
                APPLICATION_CAP_STATUS = "Approved",
                APPLICATION_CAP_STATUS_DATE = Convert.ToDateTime("2011-10-03 00:00:00.000"),
                REC_DATE = Convert.ToDateTime("2016-01-25 07:26:13.267")
            });


            AddDcbcEntity_Bbl(new DCBC_ENTITY_BBL()
            {
                DCBC_ENTITY_ID = 4,
                REC_STATUS = true,
                LAST_UPDATE = Convert.ToDateTime("2016-01-25 07:26:13.153"),
                DCBC_ENTITY_SOURCE = "BBL",
                SERV_PROV_CODE = "DC",
                B1_PER_ID1 = "15LIC",
                B1_PER_ID2 = "00000",
                B1_PER_ID3 = "22559",
                B1_PER_GROUP = "Licenses",
                B1_PER_TYPE = "Business License",
                B1_PER_SUB_TYPE = "Public Health Food Establish",
                B1_PER_CATEGORY = "Restaurant",
                B1_APPL_STATUS_ORIGINAL = "Approved",
                B1_APPL_STATUS = "Inactive",
                B1_ALT_ID = "100113000003",
                APPLICATION_CAP = "100113000004",
                B1_APPL_STATUS_DATE = "Apr 13 201",
                ISSUED_DATE = null,
                B1_HSE_NBR_START = 1723,
                B1_HSE_NBR_END = null,
                B1_HSE_FRAC_NBR_START = null,
                B1_HSE_FRAC_NBR_END = null,
                B1_UNIT_START = null,
                B1_STR_NAME = "CONNECTICUT",
                B1_STR_SUFFIX = "AVE",
                B1_STR_SUFFIX_DIR = "NW",
                B1_SITUS_CITY = "WASHINGTON",
                B1_SITUS_STATE = "DC",
                B1_SITUS_ZIP = "20009",
                FULL_ADDRESS = "1723 CONNECTICUT AV NW",
                B1_APP_TYPE_ALIAS = "Restaurant",
                SSL = "0091    0034",
                REC_FUL_NAM = "BPERRY",
                Contact_Business_Name = "SALTY DOG TAVEM",
                Contact_FirstName = "NA",
                Contact_MiddleName = null,
                Contact_LastName = "NA",
                Billing_Address1 = "1723 CONNECTICUT AVENUE N.W.",
                Billing_Address2 = null,
                Billing_Address3 = null,
                Billing_CITY = "WASHINGTON",
                Billing_STATE = "DC",
                Billing_ZIP = "20019",
                OwnrApplicant_BUSINESS_NAME = "1723 DUPONT L.L.C.",
                OwnrApplicant_FNAME = "NA",
                OwnrApplicant_MNAME = null,
                OwnrApplicant_LNAME = "NA",
                OwnrApplicant_Address1 = "1723 CONNECTICUT AVENUE N.W.",
                OwnrApplicant_Address2 = null,
                OwnrApplicant_Address3 = null,
                OwnrApplicant_CITY = "WASHINGTON",
                OwnrApplicant_STATE = "DC",
                OwnrApplicant_ZIP = "20019",
                RegAgent_BUSINESS_NAME = null,
                RegAgent_FNAME = "ALEX",
                RegAgent_MNAME = null,
                RegAgent_LNAME = "PARASKEVAS",
                RegAgent_Address1 = "6520 6th STREET N.W.",
                RegAgent_Address2 = null,
                RegAgent_Address3 = null,
                RegAgent_CITY = "WASHINGTON",
                RegAgent_STATE = "DC",
                RegAgent_ZIP = "20012",
                Attr_TRADE_NAME = "SALTY DOG TAVEM",
                Business_Org = "Limited Liability Company",
                Expiration_Date = DateTime.Now.AddDays(20).ToString("yyyy/MM/dd"),
                License_Issued_Date = "04/13/2015",
                Period_Start_Date = "4/1/2015",
                License_Category = "Restaurant",
                License_Category_Full = "Public Health: Retail Food Establishment - Restaurant",
                TaxNumber = "FEIN",
                FEIN_SSN = "202201148",
                APPLICATION_CAP_STATUS = "Approved",
                APPLICATION_CAP_STATUS_DATE = Convert.ToDateTime("2011-10-03 00:00:00.000"),
                REC_DATE = Convert.ToDateTime("2016-01-25 07:26:13.267")
            });
            AddDcbcEntity_Bbl(new DCBC_ENTITY_BBL()
            {
                DCBC_ENTITY_ID = 5,
                REC_STATUS = true,
                LAST_UPDATE = Convert.ToDateTime("2016-01-25 07:26:13.153"),
                DCBC_ENTITY_SOURCE = "BBL",
                SERV_PROV_CODE = "DC",
                B1_PER_ID1 = "15LIC",
                B1_PER_ID2 = "00000",
                B1_PER_ID3 = "22559",
                B1_PER_GROUP = "Licenses",
                B1_PER_TYPE = "Business License",
                B1_PER_SUB_TYPE = "Public Health Food Establish",
                B1_PER_CATEGORY = "Restaurant",
                B1_APPL_STATUS_ORIGINAL = "Approved",
                B1_APPL_STATUS = "Expired",
                B1_ALT_ID = "100113000005",
                APPLICATION_CAP = "100113000006",
                B1_APPL_STATUS_DATE = "Apr 13 201",
                ISSUED_DATE = null,
                B1_HSE_NBR_START = 1723,
                B1_HSE_NBR_END = null,
                B1_HSE_FRAC_NBR_START = null,
                B1_HSE_FRAC_NBR_END = null,
                B1_UNIT_START = null,
                B1_STR_NAME = "CONNECTICUT",
                B1_STR_SUFFIX = "AVE",
                B1_STR_SUFFIX_DIR = "NW",
                B1_SITUS_CITY = "WASHINGTON",
                B1_SITUS_STATE = "DC",
                B1_SITUS_ZIP = "20009",
                FULL_ADDRESS = "1723 CONNECTICUT AV NW",
                B1_APP_TYPE_ALIAS = "Restaurant",
                SSL = "0091    0034",
                REC_FUL_NAM = "BPERRY",
                Contact_Business_Name = "SALTY DOG TAVEM",
                Contact_FirstName = "NA",
                Contact_MiddleName = null,
                Contact_LastName = "NA",
                Billing_Address1 = "1723 CONNECTICUT AVENUE N.W.",
                Billing_Address2 = null,
                Billing_Address3 = null,
                Billing_CITY = "WASHINGTON",
                Billing_STATE = "DC",
                Billing_ZIP = "20019",
                OwnrApplicant_BUSINESS_NAME = null,
                OwnrApplicant_FNAME = "NA",
                OwnrApplicant_MNAME = null,
                OwnrApplicant_LNAME = "NA",
                OwnrApplicant_Address1 = "1723 CONNECTICUT AVENUE N.W.",
                OwnrApplicant_Address2 = null,
                OwnrApplicant_Address3 = null,
                OwnrApplicant_CITY = "WASHINGTON",
                OwnrApplicant_STATE = "DC",
                OwnrApplicant_ZIP = "20019",
                RegAgent_BUSINESS_NAME = null,
                RegAgent_FNAME = "ALEX",
                RegAgent_MNAME = null,
                RegAgent_LNAME = "PARASKEVAS",
                RegAgent_Address1 = "6520 6th STREET N.W.",
                RegAgent_Address2 = null,
                RegAgent_Address3 = null,
                RegAgent_CITY = "WASHINGTON",
                RegAgent_STATE = "DC",
                RegAgent_ZIP = "20012",
                Attr_TRADE_NAME = "SALTY DOG TAVEM",
                Business_Org = "Limited Liability Company",
                Expiration_Date = DateTime.Now.AddDays(100).ToString("yyyy/MM/dd"),
                License_Issued_Date = "04/13/2015",
                Period_Start_Date = "4/1/2015",
                License_Category = "Restaurant",
                License_Category_Full = "Public Health: Retail Food Establishment - Restaurant",
                TaxNumber = "SSN",
                FEIN_SSN = "579964164",
                APPLICATION_CAP_STATUS = "Approved",
                APPLICATION_CAP_STATUS_DATE = Convert.ToDateTime("2011-10-03 00:00:00.000"),
                REC_DATE = Convert.ToDateTime("2016-01-25 07:26:13.267")
            });

            AddDcbcEntity_Bbl(new DCBC_ENTITY_BBL()
            {

                DCBC_ENTITY_ID = 6,
                REC_STATUS = true,
                LAST_UPDATE = Convert.ToDateTime("2016-01-25 07:26:13.153"),
                DCBC_ENTITY_SOURCE = "BBL",
                SERV_PROV_CODE = "DC",
                B1_PER_ID1 = "13LIC",
                B1_PER_ID2 = "00000",
                B1_PER_ID3 = "28963",
                B1_PER_GROUP = "Licenses",
                B1_PER_TYPE = "Business License",
                B1_PER_SUB_TYPE = "Public Health Food Establish",
                B1_PER_CATEGORY = "Restaurant",
                B1_APPL_STATUS_ORIGINAL = "Approved",
                B1_APPL_STATUS = "Lapsed",
                B1_ALT_ID = "931313000266",
                APPLICATION_CAP = "931313000266",
                B1_APPL_STATUS_DATE = "Jul 4 201",
                ISSUED_DATE = null,
                B1_HSE_NBR_START = 1020,
                B1_HSE_NBR_END = null,
                B1_HSE_FRAC_NBR_START = null,
                B1_HSE_FRAC_NBR_END = null,
                B1_UNIT_START = "R120",
                B1_STR_NAME = "19TH",
                B1_STR_SUFFIX = "ST",
                B1_STR_SUFFIX_DIR = "NW",
                B1_SITUS_CITY = "WASHINGTON",
                B1_SITUS_STATE = "DC",
                B1_SITUS_ZIP = "20036",
                FULL_ADDRESS = "1020 19TH ST NW",
                B1_APP_TYPE_ALIAS = "Restaurant",
                SSL = "0085    0061",
                REC_FUL_NAM = "VANDERSON",
                Contact_Business_Name = "RETROSPECT COFFE AND TEA LLC",
                Contact_FirstName = "VICTOR",
                Contact_MiddleName = null,
                Contact_LastName = "CHERNYY",
                Billing_Address1 = "2120 OBSERVATORY PL NW",
                Billing_Address2 = null,
                Billing_Address3 = null,
                Billing_CITY = "WASHINGTON",
                Billing_STATE = "DC",
                Billing_ZIP = "20036",
                OwnrApplicant_BUSINESS_NAME = "RETROSPECT COFFE AND TEA LLC",
                OwnrApplicant_FNAME = "NA",
                OwnrApplicant_MNAME = null,
                OwnrApplicant_LNAME = "NA",
                OwnrApplicant_Address1 = "1020 19TH ST NW",
                OwnrApplicant_Address2 = "R120",
                OwnrApplicant_Address3 = null,
                OwnrApplicant_CITY = "WASHINGTON",
                OwnrApplicant_STATE = "DC",
                OwnrApplicant_ZIP = "20036",
                RegAgent_BUSINESS_NAME = "RETROSPECT COFFE AND TEA LLC",
                RegAgent_FNAME = "VICTOR",
                RegAgent_MNAME = null,
                RegAgent_LNAME = "CHERNYY",
                RegAgent_Address1 = "2120 OBSERVATORY PL NW",
                RegAgent_Address2 = null,
                RegAgent_Address3 = null,
                RegAgent_CITY = "WASHINGTON",
                RegAgent_STATE = "DC",
                RegAgent_ZIP = "20007",
                Attr_TRADE_NAME = null,
                Business_Org = "Limited Liability Company",
               // Expiration_Date = "6/31/2015",
                Expiration_Date = DateTime.Now.AddDays(-70).ToString("MM/dd/yyyy"),
                License_Issued_Date = DateTime.Now.AddDays(-200).ToString("yyyy/MM/dd"),
                Period_Start_Date = "7/1/2015",
                License_Category = "Restaurant",
                License_Category_Full = "Public Health: Retail Food Establishment - Restaurant",
                TaxNumber = "FEIN",
                FEIN_SSN = "217643170",
                APPLICATION_CAP_STATUS = "Billed",
                APPLICATION_CAP_STATUS_DATE = Convert.ToDateTime("2011-10-03 00:00:00.000"),
                REC_DATE = Convert.ToDateTime("2016-01-25 07:26:13.267")
            });
           

        }
    }
}