using System;
using System.Collections.Generic;
using BusinessCenter.Data;

namespace BusinessCenter.Tests.Setup
{
    public class DCBC_ENTITY_BBL_RenewalsData
    {
        private readonly List<DCBC_ENTITY_BBL_Renewals> _entities;
        public bool IsInitialized;

        public void AddDCBC_ENTITY_BBL_RenewalsEntity(DCBC_ENTITY_BBL_Renewals obj)
        {
            _entities.Add(obj);
        }

        public List<DCBC_ENTITY_BBL_Renewals> DcbcEntityBblRenewalsList
        {
            get { return _entities; }
        }

        public DCBC_ENTITY_BBL_RenewalsData()
        {
            IsInitialized = true;
            _entities = new List<DCBC_ENTITY_BBL_Renewals>();

            AddDCBC_ENTITY_BBL_RenewalsEntity(new DCBC_ENTITY_BBL_Renewals()
            {

                As_of_Date = Convert.ToDateTime("2015-09-25"),
                SERV_PROV_CODE = "DC",
                B1_PER_ID1 = "11LIC",
                B1_PER_ID2 = "00000",
                B1_PER_ID3 = "J1013",
                B1_PER_GROUP = "Licenses",
                B1_PER_TYPE = "Business License Renewal",
                B1_PER_SUB_TYPE = "NA",
                B1_PER_CATEGORY = "NA",
                B1_APP_TYPE_ALIAS = "Business License Renewal",
                b1_Alt_ID = "LREN11002680",
                License_Being_Renewed = "931315000136",
                B1_APPL_STATUS = "Billed",
                Renewal_Status = "Ready to Renew",

                B1_HSE_NBR_START = 805,
                B1_HSE_NBR_END = null,
                B1_HSE_FRAC_NBR_START = "",
                B1_UNIT_START = "",
                B1_STR_NAME = "FLORIDA",
                B1_STR_SUFFIX = "AVE",
                B1_STR_SUFFIX_DIR = "NW",
                B1_SITUS_CITY = "WASHINGTON",
                B1_SITUS_STATE = "DC",
                B1_SITUS_ZIP = "2007",
                License_Period = "",
                OSR_Pin = "184952",
                CofO_Number = "CO0902367",
                Review_Necessary = "CHECKED",
                CofO_IssueDate = "06/22/2009",
                Contact_Business_Name = "CAPITOL EDGE LLC",
                Contact_FirstName = "NA",
                Contact_MiddleName = "",
                Contact_LastName = "NA",
                Billing_Address1 = "805 C ST NE ",
                Billing_Address2 = "",
                Billing_Address3 = "",
                Billing_CITY = "WASHINGTON",
                Billing_STATE = "DC",
                Billing_ZIP = "20002",
                OwnrApplicant_BUSINESS_NAME = "CAPITOL EDGE LLC",
                OwnrApplicant_FNAME = "NA",
                OwnrApplicant_MNAME = "NA",
                OwnrApplicant_LNAME = "NA",
                OwnrApplicant_Address1 = "805 C ST NE ",
                OwnrApplicant_Address2 = "",
                OwnrApplicant_Address3 = "",
                OwnrApplicant_CITY = "WASHINGTON",
                OwnrApplicant_STATE = "DC",
                OwnrApplicant_ZIP = "20002",
                RegAgent_BUSINESS_NAME = "S AND P REGISTERED AGENTS INC",
                RegAgent_FNAME = "NA",
                RegAgent_MNAME = "",
                RegAgent_LNAME = "NA",
                RegAgent_Address1 = "1008 PENNSYLVANIA AVE SE ",
                RegAgent_Address2 = "",
                RegAgent_Address3 = "",
                RegAgent_CITY = "WASHINGTON",
                RegAgent_STATE = "DC",
                RegAgent_ZIP = "20003",
                Attr_TRADE_NAME = "",
                Business_Org = "SOLE PROPRIETORSHIP",
                B1_APPL_STATUS_DATE=DateTime.Now



               
            });

            AddDCBC_ENTITY_BBL_RenewalsEntity(new DCBC_ENTITY_BBL_Renewals()
            {
                As_of_Date = Convert.ToDateTime("2015-09-25"),
                SERV_PROV_CODE = "DC",
                B1_PER_ID1 = "11LIC",
                B1_PER_ID2 = "00000",
                B1_PER_ID3 = "J1013",
                B1_PER_GROUP = "Licenses",
                B1_PER_TYPE = "Business License Renewal",
                B1_PER_SUB_TYPE = "NA",
                B1_PER_CATEGORY = "NA",
                B1_APP_TYPE_ALIAS = "Business License Renewal",
                b1_Alt_ID = "LREN11002681",
                License_Being_Renewed = "931315000136",
                B1_APPL_STATUS = "Billed",
                Renewal_Status = "Ready to Renew",

                B1_HSE_NBR_START = 805,
                B1_HSE_NBR_END = null,
                B1_HSE_FRAC_NBR_START = "",
                B1_UNIT_START = "",
                B1_STR_NAME = "FLORIDA",
                B1_STR_SUFFIX = "AVE",
                B1_STR_SUFFIX_DIR = "NW",
                B1_SITUS_CITY = "WASHINGTON",
                B1_SITUS_STATE = "DC",
                B1_SITUS_ZIP = "2007",
                License_Period = "",
                OSR_Pin = "148791",
                CofO_Number = "CO0902545",
                Review_Necessary = "CHECKED",
                CofO_IssueDate = "06/22/2009",
                Contact_Business_Name = "CAPITOL EDGE LLC",
                Contact_FirstName = "NA",
                Contact_MiddleName = "",
                Contact_LastName = "NA",
                Billing_Address1 = "805 C ST NE ",
                Billing_Address2 = "",
                Billing_Address3 = "",
                Billing_CITY = "WASHINGTON",
                Billing_STATE = "DC",
                Billing_ZIP = "20002",
                OwnrApplicant_BUSINESS_NAME = "CAPITOL EDGE LLC",
                OwnrApplicant_FNAME = "NA",
                OwnrApplicant_MNAME = "",
                OwnrApplicant_LNAME = "NA",
                OwnrApplicant_Address1 = "805 C ST NE ",
                OwnrApplicant_Address2 = "",
                OwnrApplicant_Address3 = "",
                OwnrApplicant_CITY = "WASHINGTON",
                OwnrApplicant_STATE = "DC",
                OwnrApplicant_ZIP = "20002",
                RegAgent_BUSINESS_NAME = "S AND P REGISTERED AGENTS INC",
                RegAgent_FNAME = "NA",
                RegAgent_MNAME = "",
                RegAgent_LNAME = "NA",
                RegAgent_Address1 = "1008 PENNSYLVANIA AVE SE ",
                RegAgent_Address2 = "",
                RegAgent_Address3 = "",
                RegAgent_CITY = "WASHINGTON",
                RegAgent_STATE = "DC",
                RegAgent_ZIP = "20003",
                Attr_TRADE_NAME = "",
                Business_Org = "",
                B1_APPL_STATUS_DATE = DateTime.Now
            });

            AddDCBC_ENTITY_BBL_RenewalsEntity(new DCBC_ENTITY_BBL_Renewals()
            {
                As_of_Date = Convert.ToDateTime("2015-09-25"),
                SERV_PROV_CODE = "DC",
                B1_PER_ID1 = "11LIC",
                B1_PER_ID2 = "00000",
                B1_PER_ID3 = "J1013",
                B1_PER_GROUP = "Licenses",
                B1_PER_TYPE = "Business License Renewal",
                B1_PER_SUB_TYPE = "NA",
                B1_PER_CATEGORY = "NA",
                B1_APP_TYPE_ALIAS = "Business License Renewal",
                b1_Alt_ID = "LREN13018589",
                License_Being_Renewed = "400312000307",
                B1_APPL_STATUS = "Billed",
                Renewal_Status = "Ready to Renew",

                B1_HSE_NBR_START = 805,
                B1_HSE_NBR_END = null,
                B1_HSE_FRAC_NBR_START = "",
                B1_UNIT_START = "",
                B1_STR_NAME = "FLORIDA",
                B1_STR_SUFFIX = "AVE",
                B1_STR_SUFFIX_DIR = "NW",
                B1_SITUS_CITY = "WASHINGTON",
                B1_SITUS_STATE = "DC",
                B1_SITUS_ZIP = "2007",
                License_Period = "",
                OSR_Pin = "811578",
                CofO_Number = "CO1103151",
                Review_Necessary = "CHECKED",
                CofO_IssueDate = "12/15/2011",
                Contact_Business_Name = "CAPITOL EDGE LLC",
                Contact_FirstName = "NA",
                Contact_MiddleName = "",
                Contact_LastName = "NA",
                Billing_Address1 = "805 C ST NE ",
                Billing_Address2 = "",
                Billing_Address3 = "",
                Billing_CITY = "WASHINGTON",
                Billing_STATE = "DC",
                Billing_ZIP = "20002",
                OwnrApplicant_BUSINESS_NAME = "CAPITOL EDGE LLC",
                OwnrApplicant_FNAME = "NA",
                OwnrApplicant_MNAME = "",
                OwnrApplicant_LNAME = "NA",
                OwnrApplicant_Address1 = "805 C ST NE ",
                OwnrApplicant_Address2 = "",
                OwnrApplicant_Address3 = "",
                OwnrApplicant_CITY = "WASHINGTON",
                OwnrApplicant_STATE = "DC",
                OwnrApplicant_ZIP = "20002",
                RegAgent_BUSINESS_NAME = "S AND P REGISTERED AGENTS INC",
                RegAgent_FNAME = "NA",
                RegAgent_MNAME = "",
                RegAgent_LNAME = "NA",
                RegAgent_Address1 = "1008 PENNSYLVANIA AVE SE ",
                RegAgent_Address2 = "",
                RegAgent_Address3 = "",
                RegAgent_CITY = "WASHINGTON",
                RegAgent_STATE = "DC",
                RegAgent_ZIP = "20003",
                Attr_TRADE_NAME = "",
                Business_Org = "",
                B1_APPL_STATUS_DATE = DateTime.Now
            });
            AddDCBC_ENTITY_BBL_RenewalsEntity(new DCBC_ENTITY_BBL_Renewals()
            {
                As_of_Date = Convert.ToDateTime("2016-02-08"),
                SERV_PROV_CODE = "DC",
                B1_PER_ID1 = "14LIC",
                B1_PER_ID2 = "00000",
                B1_PER_ID3 = "17623",
                B1_PER_GROUP = "Licenses",
                B1_PER_TYPE = "Business License Renewal",
                B1_PER_SUB_TYPE = "NA",
                B1_PER_CATEGORY = "NA",
                B1_APP_TYPE_ALIAS = "Business License Renewal",
                b1_Alt_ID = "LREN13018589",
                License_Being_Renewed = "400312000720",
                B1_APPL_STATUS = "Billed",
                Renewal_Status = "Expired",

                B1_HSE_NBR_START = 805,
                B1_HSE_NBR_END = null,
                B1_HSE_FRAC_NBR_START = "",
                B1_UNIT_START = "",
                B1_STR_NAME = "FLORIDA",
                B1_STR_SUFFIX = "AVE",
                B1_STR_SUFFIX_DIR = "NW",
                B1_SITUS_CITY = "WASHINGTON",
                B1_SITUS_STATE = "DC",
                B1_SITUS_ZIP = "2007",
                License_Period = "",
                OSR_Pin = "811578",
                CofO_Number = "CO1103151",
                Review_Necessary = "CHECKED",
                CofO_IssueDate = "12/15/2011",
                Contact_Business_Name = "CAPITOL EDGE LLC",
                Contact_FirstName = "NA",
                Contact_MiddleName = "",
                Contact_LastName = "NA",
                Billing_Address1 = "805 C ST NE ",
                Billing_Address2 = "",
                Billing_Address3 = "",
                Billing_CITY = "WASHINGTON",
                Billing_STATE = "DC",
                Billing_ZIP = "20002",
                OwnrApplicant_BUSINESS_NAME = "CAPITOL EDGE LLC",
                OwnrApplicant_FNAME = "NA",
                OwnrApplicant_MNAME = "",
                OwnrApplicant_LNAME = "NA",
                OwnrApplicant_Address1 = "805 C ST NE ",
                OwnrApplicant_Address2 = "",
                OwnrApplicant_Address3 = "",
                OwnrApplicant_CITY = "WASHINGTON",
                OwnrApplicant_STATE = "DC",
                OwnrApplicant_ZIP = "20002",
                RegAgent_BUSINESS_NAME = "S AND P REGISTERED AGENTS INC",
                RegAgent_FNAME = "NA",
                RegAgent_MNAME = "",
                RegAgent_LNAME = "NA",
                RegAgent_Address1 = "1008 PENNSYLVANIA AVE SE ",
                RegAgent_Address2 = "",
                RegAgent_Address3 = "",
                RegAgent_CITY = "WASHINGTON",
                RegAgent_STATE = "DC",
                RegAgent_ZIP = "20003",
                Attr_TRADE_NAME = "",
                Business_Org = "",
                B1_APPL_STATUS_DATE = DateTime.Now
            });

         				
        }
    }
}