//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessCenter.Api.BusinessLocation {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://tempuri.org/newWebServices/LocationVerifier", ConfigurationName="BusinessLocation.LocationVerifierSoap")]
    public interface LocationVerifierSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/newWebServices/LocationVerifier/verifyDCAddressThrouString", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        BusinessCenter.Api.BusinessLocation.ReturnObject verifyDCAddressThrouString(string Address);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/newWebServices/LocationVerifier/verifyDCAddressThrouString", ReplyAction="*")]
        System.Threading.Tasks.Task<BusinessCenter.Api.BusinessLocation.ReturnObject> verifyDCAddressThrouStringAsync(string Address);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/newWebServices/LocationVerifier/verifyDCAddressThrouString2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        BusinessCenter.Api.BusinessLocation.ReturnObject verifyDCAddressThrouString2(string Address, string f);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/newWebServices/LocationVerifier/verifyDCAddressThrouString2", ReplyAction="*")]
        System.Threading.Tasks.Task<BusinessCenter.Api.BusinessLocation.ReturnObject> verifyDCAddressThrouString2Async(string Address, string f);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/newWebServices/LocationVerifier/verifyDCAddressThrouComponents" +
            "", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        BusinessCenter.Api.BusinessLocation.ReturnObject verifyDCAddressThrouComponents(string AddNumber, string AddNumberSuffix, string StName, string StType, string Quad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/newWebServices/LocationVerifier/verifyDCAddressThrouComponents" +
            "", ReplyAction="*")]
        System.Threading.Tasks.Task<BusinessCenter.Api.BusinessLocation.ReturnObject> verifyDCAddressThrouComponentsAsync(string AddNumber, string AddNumberSuffix, string StName, string StType, string Quad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/newWebServices/LocationVerifier/verifyDCAddressThrouComponents" +
            "2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        BusinessCenter.Api.BusinessLocation.ReturnObject verifyDCAddressThrouComponents2(string AddNumber, string AddNumberSuffix, string StName, string StType, string Quad, string f);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/newWebServices/LocationVerifier/verifyDCAddressThrouComponents" +
            "2", ReplyAction="*")]
        System.Threading.Tasks.Task<BusinessCenter.Api.BusinessLocation.ReturnObject> verifyDCAddressThrouComponents2Async(string AddNumber, string AddNumberSuffix, string StName, string StType, string Quad, string f);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/newWebServices/LocationVerifier/findOutsideLocation", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        BusinessCenter.Api.BusinessLocation.ReturnObject findOutsideLocation(string Location, string City, string State, string Zipcode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/newWebServices/LocationVerifier/findOutsideLocation", ReplyAction="*")]
        System.Threading.Tasks.Task<BusinessCenter.Api.BusinessLocation.ReturnObject> findOutsideLocationAsync(string Location, string City, string State, string Zipcode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/newWebServices/LocationVerifier/findOutsideLocation2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        BusinessCenter.Api.BusinessLocation.ReturnObject findOutsideLocation2(string Location, string City, string State, string Zipcode, string f);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/newWebServices/LocationVerifier/findOutsideLocation2", ReplyAction="*")]
        System.Threading.Tasks.Task<BusinessCenter.Api.BusinessLocation.ReturnObject> findOutsideLocation2Async(string Location, string City, string State, string Zipcode, string f);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/newWebServices/LocationVerifier/findInOutsideLocation", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        BusinessCenter.Api.BusinessLocation.ReturnObject findInOutsideLocation(string Location, string City, string State, string Zipcode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/newWebServices/LocationVerifier/findInOutsideLocation", ReplyAction="*")]
        System.Threading.Tasks.Task<BusinessCenter.Api.BusinessLocation.ReturnObject> findInOutsideLocationAsync(string Location, string City, string State, string Zipcode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/newWebServices/LocationVerifier/findInOutsideLocation2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        BusinessCenter.Api.BusinessLocation.ReturnObject findInOutsideLocation2(string Location, string City, string State, string Zipcode, string f);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/newWebServices/LocationVerifier/findInOutsideLocation2", ReplyAction="*")]
        System.Threading.Tasks.Task<BusinessCenter.Api.BusinessLocation.ReturnObject> findInOutsideLocation2Async(string Location, string City, string State, string Zipcode, string f);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/newWebServices/LocationVerifier/findDCInterThrouString", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        BusinessCenter.Api.BusinessLocation.ReturnObject findDCInterThrouString(string Intersection);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/newWebServices/LocationVerifier/findDCInterThrouString", ReplyAction="*")]
        System.Threading.Tasks.Task<BusinessCenter.Api.BusinessLocation.ReturnObject> findDCInterThrouStringAsync(string Intersection);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/newWebServices/LocationVerifier/findDCInterThrouString2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        BusinessCenter.Api.BusinessLocation.ReturnObject findDCInterThrouString2(string Intersection, string f);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/newWebServices/LocationVerifier/findDCInterThrouString2", ReplyAction="*")]
        System.Threading.Tasks.Task<BusinessCenter.Api.BusinessLocation.ReturnObject> findDCInterThrouString2Async(string Intersection, string f);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/newWebServices/LocationVerifier/findDCInterThrouComponents", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        BusinessCenter.Api.BusinessLocation.ReturnObject findDCInterThrouComponents(string crossstreet1, string crossstreet2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/newWebServices/LocationVerifier/findDCInterThrouComponents", ReplyAction="*")]
        System.Threading.Tasks.Task<BusinessCenter.Api.BusinessLocation.ReturnObject> findDCInterThrouComponentsAsync(string crossstreet1, string crossstreet2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/newWebServices/LocationVerifier/findDCInterThrouComponents2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        BusinessCenter.Api.BusinessLocation.ReturnObject findDCInterThrouComponents2(string crossstreet1, string crossstreet2, string f);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/newWebServices/LocationVerifier/findDCInterThrouComponents2", ReplyAction="*")]
        System.Threading.Tasks.Task<BusinessCenter.Api.BusinessLocation.ReturnObject> findDCInterThrouComponents2Async(string crossstreet1, string crossstreet2, string f);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/newWebServices/LocationVerifier/findDCInterThrouThreeComponent" +
            "s", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        BusinessCenter.Api.BusinessLocation.ReturnObject findDCInterThrouThreeComponents(string crossstreet1, string xtype, string crossstreet2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/newWebServices/LocationVerifier/findDCInterThrouThreeComponent" +
            "s", ReplyAction="*")]
        System.Threading.Tasks.Task<BusinessCenter.Api.BusinessLocation.ReturnObject> findDCInterThrouThreeComponentsAsync(string crossstreet1, string xtype, string crossstreet2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/newWebServices/LocationVerifier/findDCInterThrouThreeComponent" +
            "s2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        BusinessCenter.Api.BusinessLocation.ReturnObject findDCInterThrouThreeComponents2(string crossstreet1, string xtype, string crossstreet2, string f);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/newWebServices/LocationVerifier/findDCInterThrouThreeComponent" +
            "s2", ReplyAction="*")]
        System.Threading.Tasks.Task<BusinessCenter.Api.BusinessLocation.ReturnObject> findDCInterThrouThreeComponents2Async(string crossstreet1, string xtype, string crossstreet2, string f);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/newWebServices/LocationVerifier/findDCBlkThrouString", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        BusinessCenter.Api.BusinessLocation.ReturnObject findDCBlkThrouString(string Block);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/newWebServices/LocationVerifier/findDCBlkThrouString", ReplyAction="*")]
        System.Threading.Tasks.Task<BusinessCenter.Api.BusinessLocation.ReturnObject> findDCBlkThrouStringAsync(string Block);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/newWebServices/LocationVerifier/findDCBlkThrouString2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        BusinessCenter.Api.BusinessLocation.ReturnObject findDCBlkThrouString2(string Block, string f);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/newWebServices/LocationVerifier/findDCBlkThrouString2", ReplyAction="*")]
        System.Threading.Tasks.Task<BusinessCenter.Api.BusinessLocation.ReturnObject> findDCBlkThrouString2Async(string Block, string f);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/newWebServices/LocationVerifier/findDCBlkThrouComponents", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        BusinessCenter.Api.BusinessLocation.ReturnObject findDCBlkThrouComponents(string onstreet, string fromstreet, string tostreet);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/newWebServices/LocationVerifier/findDCBlkThrouComponents", ReplyAction="*")]
        System.Threading.Tasks.Task<BusinessCenter.Api.BusinessLocation.ReturnObject> findDCBlkThrouComponentsAsync(string onstreet, string fromstreet, string tostreet);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/newWebServices/LocationVerifier/findDCBlkThrouComponents2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        BusinessCenter.Api.BusinessLocation.ReturnObject findDCBlkThrouComponents2(string onstreet, string fromstreet, string tostreet, string f);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/newWebServices/LocationVerifier/findDCBlkThrouComponents2", ReplyAction="*")]
        System.Threading.Tasks.Task<BusinessCenter.Api.BusinessLocation.ReturnObject> findDCBlkThrouComponents2Async(string onstreet, string fromstreet, string tostreet, string f);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/newWebServices/LocationVerifier/findAddFromSSL", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        BusinessCenter.Api.BusinessLocation.ReturnObject findAddFromSSL(string Square, string Suffix, string Lot);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/newWebServices/LocationVerifier/findAddFromSSL", ReplyAction="*")]
        System.Threading.Tasks.Task<BusinessCenter.Api.BusinessLocation.ReturnObject> findAddFromSSLAsync(string Square, string Suffix, string Lot);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/newWebServices/LocationVerifier/findAddFromPlace", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        BusinessCenter.Api.BusinessLocation.ReturnObject findAddFromPlace(string Place);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/newWebServices/LocationVerifier/findAddFromPlace", ReplyAction="*")]
        System.Threading.Tasks.Task<BusinessCenter.Api.BusinessLocation.ReturnObject> findAddFromPlaceAsync(string Place);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/newWebServices/LocationVerifier/findAddFromPlace2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        BusinessCenter.Api.BusinessLocation.ReturnObject findAddFromPlace2(string Place, string f);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/newWebServices/LocationVerifier/findAddFromPlace2", ReplyAction="*")]
        System.Threading.Tasks.Task<BusinessCenter.Api.BusinessLocation.ReturnObject> findAddFromPlace2Async(string Place, string f);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/newWebServices/LocationVerifier/findAID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        BusinessCenter.Api.BusinessLocation.ReturnObject findAID(string AID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/newWebServices/LocationVerifier/findAID", ReplyAction="*")]
        System.Threading.Tasks.Task<BusinessCenter.Api.BusinessLocation.ReturnObject> findAIDAsync(string AID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/newWebServices/LocationVerifier/findAID2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        BusinessCenter.Api.BusinessLocation.ReturnObject findAID2(string AID, string f);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/newWebServices/LocationVerifier/findAID2", ReplyAction="*")]
        System.Threading.Tasks.Task<BusinessCenter.Api.BusinessLocation.ReturnObject> findAID2Async(string AID, string f);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/newWebServices/LocationVerifier/findLocation", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        BusinessCenter.Api.BusinessLocation.ReturnObject findLocation(string str);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/newWebServices/LocationVerifier/findLocation", ReplyAction="*")]
        System.Threading.Tasks.Task<BusinessCenter.Api.BusinessLocation.ReturnObject> findLocationAsync(string str);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/newWebServices/LocationVerifier/findLocation2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        BusinessCenter.Api.BusinessLocation.ReturnObject findLocation2(string str, string f);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/newWebServices/LocationVerifier/findLocation2", ReplyAction="*")]
        System.Threading.Tasks.Task<BusinessCenter.Api.BusinessLocation.ReturnObject> findLocation2Async(string str, string f);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/newWebServices/LocationVerifier/findLocationBatch", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        object[] findLocationBatch(string addr_base64, string addr_separator, string chunkSequnce_separator);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/newWebServices/LocationVerifier/findLocationBatch", ReplyAction="*")]
        System.Threading.Tasks.Task<object[]> findLocationBatchAsync(string addr_base64, string addr_separator, string chunkSequnce_separator);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/newWebServices/LocationVerifier/findLocationBatch2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        object[] findLocationBatch2(string addr_base64, string addr_separator, string chunkSequnce_separator, string f);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/newWebServices/LocationVerifier/findLocationBatch2", ReplyAction="*")]
        System.Threading.Tasks.Task<object[]> findLocationBatch2Async(string addr_base64, string addr_separator, string chunkSequnce_separator, string f);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/newWebServices/LocationVerifier/findRdWySegIDFromMiniMARID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        BusinessCenter.Api.BusinessLocation.ReturnObject findRdWySegIDFromMiniMARID(string MiniMARADDID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/newWebServices/LocationVerifier/findRdWySegIDFromMiniMARID", ReplyAction="*")]
        System.Threading.Tasks.Task<BusinessCenter.Api.BusinessLocation.ReturnObject> findRdWySegIDFromMiniMARIDAsync(string MiniMARADDID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/newWebServices/LocationVerifier/findRdWySegIDFromMiniMARID2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        BusinessCenter.Api.BusinessLocation.ReturnObject findRdWySegIDFromMiniMARID2(string MiniMARADDID, string f);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/newWebServices/LocationVerifier/findRdWySegIDFromMiniMARID2", ReplyAction="*")]
        System.Threading.Tasks.Task<BusinessCenter.Api.BusinessLocation.ReturnObject> findRdWySegIDFromMiniMARID2Async(string MiniMARADDID, string f);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/newWebServices/LocationVerifier/findDCBlkFromIntersection", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Data.DataSet findDCBlkFromIntersection(string crossstreet1, string crossstreet2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/newWebServices/LocationVerifier/findDCBlkFromIntersection", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> findDCBlkFromIntersectionAsync(string crossstreet1, string crossstreet2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/newWebServices/LocationVerifier/findDCBlkFromIntersection2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Data.DataSet findDCBlkFromIntersection2(string crossstreet1, string crossstreet2, string f);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/newWebServices/LocationVerifier/findDCBlkFromIntersection2", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> findDCBlkFromIntersection2Async(string crossstreet1, string crossstreet2, string f);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/newWebServices/LocationVerifier/findMARIDFromMiniMARID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        BusinessCenter.Api.BusinessLocation.ReturnObject findMARIDFromMiniMARID(string minimarid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/newWebServices/LocationVerifier/findMARIDFromMiniMARID", ReplyAction="*")]
        System.Threading.Tasks.Task<BusinessCenter.Api.BusinessLocation.ReturnObject> findMARIDFromMiniMARIDAsync(string minimarid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/newWebServices/LocationVerifier/findMARIDFromMiniMARID2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        BusinessCenter.Api.BusinessLocation.ReturnObject findMARIDFromMiniMARID2(string minimarid, string f);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/newWebServices/LocationVerifier/findMARIDFromMiniMARID2", ReplyAction="*")]
        System.Threading.Tasks.Task<BusinessCenter.Api.BusinessLocation.ReturnObject> findMARIDFromMiniMARID2Async(string minimarid, string f);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/newWebServices/LocationVerifier/findMiniMARIDFromMARID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        BusinessCenter.Api.BusinessLocation.ReturnObject findMiniMARIDFromMARID(string marid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/newWebServices/LocationVerifier/findMiniMARIDFromMARID", ReplyAction="*")]
        System.Threading.Tasks.Task<BusinessCenter.Api.BusinessLocation.ReturnObject> findMiniMARIDFromMARIDAsync(string marid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/newWebServices/LocationVerifier/findMiniMARIDFromMARID2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        BusinessCenter.Api.BusinessLocation.ReturnObject findMiniMARIDFromMARID2(string marid, string f);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/newWebServices/LocationVerifier/findMiniMARIDFromMARID2", ReplyAction="*")]
        System.Threading.Tasks.Task<BusinessCenter.Api.BusinessLocation.ReturnObject> findMiniMARIDFromMARID2Async(string marid, string f);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/newWebServices/LocationVerifier/reverseGeocoding", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Data.DataSet reverseGeocoding(string x, string y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/newWebServices/LocationVerifier/reverseGeocoding", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> reverseGeocodingAsync(string x, string y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/newWebServices/LocationVerifier/reverseGeocoding2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Data.DataSet reverseGeocoding2(string x, string y, string f);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/newWebServices/LocationVerifier/reverseGeocoding2", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> reverseGeocoding2Async(string x, string y, string f);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/newWebServices/LocationVerifier/reverseLatLngGeocoding", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Data.DataSet reverseLatLngGeocoding(string lat, string lng);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/newWebServices/LocationVerifier/reverseLatLngGeocoding", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> reverseLatLngGeocodingAsync(string lat, string lng);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/newWebServices/LocationVerifier/reverseLatLngGeocoding2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Data.DataSet reverseLatLngGeocoding2(string lat, string lng, string f);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/newWebServices/LocationVerifier/reverseLatLngGeocoding2", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> reverseLatLngGeocoding2Async(string lat, string lng, string f);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/newWebServices/LocationVerifier/submitAddress", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        BusinessCenter.Api.BusinessLocation.submitReturnObj submitAddress(string address, string name, string agency, string phone, string email, string source, string comment, string withVerification);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/newWebServices/LocationVerifier/submitAddress", ReplyAction="*")]
        System.Threading.Tasks.Task<BusinessCenter.Api.BusinessLocation.submitReturnObj> submitAddressAsync(string address, string name, string agency, string phone, string email, string source, string comment, string withVerification);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/newWebServices/LocationVerifier/submitAddress2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        BusinessCenter.Api.BusinessLocation.submitReturnObj submitAddress2(string address, string name, string agency, string phone, string email, string source, string comment, string withVerification, string f);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/newWebServices/LocationVerifier/submitAddress2", ReplyAction="*")]
        System.Threading.Tasks.Task<BusinessCenter.Api.BusinessLocation.submitReturnObj> submitAddress2Async(string address, string name, string agency, string phone, string email, string source, string comment, string withVerification, string f);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/newWebServices/LocationVerifier/findAddFromSSL_new", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        BusinessCenter.Api.BusinessLocation.ReturnObject findAddFromSSL_new(string Square, string Suffix, string Lot);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/newWebServices/LocationVerifier/findAddFromSSL_new", ReplyAction="*")]
        System.Threading.Tasks.Task<BusinessCenter.Api.BusinessLocation.ReturnObject> findAddFromSSL_newAsync(string Square, string Suffix, string Lot);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/newWebServices/LocationVerifier/findAddFromSSL_new2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        BusinessCenter.Api.BusinessLocation.ReturnObject findAddFromSSL_new2(string Square, string Suffix, string Lot, string f);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/newWebServices/LocationVerifier/findAddFromSSL_new2", ReplyAction="*")]
        System.Threading.Tasks.Task<BusinessCenter.Api.BusinessLocation.ReturnObject> findAddFromSSL_new2Async(string Square, string Suffix, string Lot, string f);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/newWebServices/LocationVerifier/findAddFromSSL2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        BusinessCenter.Api.BusinessLocation.ReturnObject findAddFromSSL2(string Square, string Suffix, string Lot, string f);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/newWebServices/LocationVerifier/findAddFromSSL2", ReplyAction="*")]
        System.Threading.Tasks.Task<BusinessCenter.Api.BusinessLocation.ReturnObject> findAddFromSSL2Async(string Square, string Suffix, string Lot, string f);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/newWebServices/LocationVerifier/findSSLFromAID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        BusinessCenter.Api.BusinessLocation.ReturnObject findSSLFromAID(string AID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/newWebServices/LocationVerifier/findSSLFromAID", ReplyAction="*")]
        System.Threading.Tasks.Task<BusinessCenter.Api.BusinessLocation.ReturnObject> findSSLFromAIDAsync(string AID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/newWebServices/LocationVerifier/findSSLFromAID2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        BusinessCenter.Api.BusinessLocation.ReturnObject findSSLFromAID2(string AID, string f);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/newWebServices/LocationVerifier/findSSLFromAID2", ReplyAction="*")]
        System.Threading.Tasks.Task<BusinessCenter.Api.BusinessLocation.ReturnObject> findSSLFromAID2Async(string AID, string f);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/newWebServices/LocationVerifier/FindCondoUnitFromAID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        BusinessCenter.Api.BusinessLocation.ReturnObject FindCondoUnitFromAID(string AID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/newWebServices/LocationVerifier/FindCondoUnitFromAID", ReplyAction="*")]
        System.Threading.Tasks.Task<BusinessCenter.Api.BusinessLocation.ReturnObject> FindCondoUnitFromAIDAsync(string AID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/newWebServices/LocationVerifier/FindCondoUnitFromAID2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        BusinessCenter.Api.BusinessLocation.ReturnObject FindCondoUnitFromAID2(string AID, string f);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/newWebServices/LocationVerifier/FindCondoUnitFromAID2", ReplyAction="*")]
        System.Threading.Tasks.Task<BusinessCenter.Api.BusinessLocation.ReturnObject> FindCondoUnitFromAID2Async(string AID, string f);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/newWebServices/LocationVerifier/findAliasFromAID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        BusinessCenter.Api.BusinessLocation.ReturnObject findAliasFromAID(string AID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/newWebServices/LocationVerifier/findAliasFromAID", ReplyAction="*")]
        System.Threading.Tasks.Task<BusinessCenter.Api.BusinessLocation.ReturnObject> findAliasFromAIDAsync(string AID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/newWebServices/LocationVerifier/findAliasFromAID2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        BusinessCenter.Api.BusinessLocation.ReturnObject findAliasFromAID2(string AID, string f);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/newWebServices/LocationVerifier/findAliasFromAID2", ReplyAction="*")]
        System.Threading.Tasks.Task<BusinessCenter.Api.BusinessLocation.ReturnObject> findAliasFromAID2Async(string AID, string f);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/newWebServices/LocationVerifier/findOwnerFromSSL", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        BusinessCenter.Api.BusinessLocation.ReturnObject findOwnerFromSSL(string Square, string Suffix, string Lot);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/newWebServices/LocationVerifier/findOwnerFromSSL", ReplyAction="*")]
        System.Threading.Tasks.Task<BusinessCenter.Api.BusinessLocation.ReturnObject> findOwnerFromSSLAsync(string Square, string Suffix, string Lot);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/newWebServices/LocationVerifier/findOwnerFromSSL2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        BusinessCenter.Api.BusinessLocation.ReturnObject findOwnerFromSSL2(string Square, string Suffix, string Lot, string f);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/newWebServices/LocationVerifier/findOwnerFromSSL2", ReplyAction="*")]
        System.Threading.Tasks.Task<BusinessCenter.Api.BusinessLocation.ReturnObject> findOwnerFromSSL2Async(string Square, string Suffix, string Lot, string f);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/newWebServices/LocationVerifier/findSSLFromSquareSuffix", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        BusinessCenter.Api.BusinessLocation.ReturnObject findSSLFromSquareSuffix(string Square, string Suffix);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/newWebServices/LocationVerifier/findSSLFromSquareSuffix", ReplyAction="*")]
        System.Threading.Tasks.Task<BusinessCenter.Api.BusinessLocation.ReturnObject> findSSLFromSquareSuffixAsync(string Square, string Suffix);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/newWebServices/LocationVerifier/findSSLFromSquareSuffix2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        BusinessCenter.Api.BusinessLocation.ReturnObject findSSLFromSquareSuffix2(string Square, string Suffix, string f);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/newWebServices/LocationVerifier/findSSLFromSquareSuffix2", ReplyAction="*")]
        System.Threading.Tasks.Task<BusinessCenter.Api.BusinessLocation.ReturnObject> findSSLFromSquareSuffix2Async(string Square, string Suffix, string f);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/newWebServices/LocationVerifier/FindUnitFromAID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        BusinessCenter.Api.BusinessLocation.ReturnObject FindUnitFromAID(string AID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/newWebServices/LocationVerifier/FindUnitFromAID", ReplyAction="*")]
        System.Threading.Tasks.Task<BusinessCenter.Api.BusinessLocation.ReturnObject> FindUnitFromAIDAsync(string AID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/newWebServices/LocationVerifier/FindUnitFromAID2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        BusinessCenter.Api.BusinessLocation.ReturnObject FindUnitFromAID2(string AID, string f);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/newWebServices/LocationVerifier/FindUnitFromAID2", ReplyAction="*")]
        System.Threading.Tasks.Task<BusinessCenter.Api.BusinessLocation.ReturnObject> FindUnitFromAID2Async(string AID, string f);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/newWebServices/LocationVerifier/findROW", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        BusinessCenter.Api.BusinessLocation.ReturnObject findROW(string roadwaysegid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/newWebServices/LocationVerifier/findROW", ReplyAction="*")]
        System.Threading.Tasks.Task<BusinessCenter.Api.BusinessLocation.ReturnObject> findROWAsync(string roadwaysegid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/newWebServices/LocationVerifier/findROW2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        BusinessCenter.Api.BusinessLocation.ReturnObject findROW2(string roadwaysegid, string f);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/newWebServices/LocationVerifier/findROW2", ReplyAction="*")]
        System.Threading.Tasks.Task<BusinessCenter.Api.BusinessLocation.ReturnObject> findROW2Async(string roadwaysegid, string f);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/newWebServices/LocationVerifier/getDCStreetNames", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        BusinessCenter.Api.BusinessLocation.ReturnObject getDCStreetNames(string quad, string initialetters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/newWebServices/LocationVerifier/getDCStreetNames", ReplyAction="*")]
        System.Threading.Tasks.Task<BusinessCenter.Api.BusinessLocation.ReturnObject> getDCStreetNamesAsync(string quad, string initialetters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/newWebServices/LocationVerifier/getDCStreetNames2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        BusinessCenter.Api.BusinessLocation.ReturnObject getDCStreetNames2(string quad, string initialetters, string f);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/newWebServices/LocationVerifier/getDCStreetNames2", ReplyAction="*")]
        System.Threading.Tasks.Task<BusinessCenter.Api.BusinessLocation.ReturnObject> getDCStreetNames2Async(string quad, string initialetters, string f);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/newWebServices/LocationVerifier/getDCAddresses", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        BusinessCenter.Api.BusinessLocation.ReturnObject getDCAddresses(string initialetters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/newWebServices/LocationVerifier/getDCAddresses", ReplyAction="*")]
        System.Threading.Tasks.Task<BusinessCenter.Api.BusinessLocation.ReturnObject> getDCAddressesAsync(string initialetters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/newWebServices/LocationVerifier/getDCAddresses2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        BusinessCenter.Api.BusinessLocation.ReturnObject getDCAddresses2(string initialetters, string f);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/newWebServices/LocationVerifier/getDCAddresses2", ReplyAction="*")]
        System.Threading.Tasks.Task<BusinessCenter.Api.BusinessLocation.ReturnObject> getDCAddresses2Async(string initialetters, string f);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/newWebServices/LocationVerifier/getDCParkingMeter", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        BusinessCenter.Api.BusinessLocation.ReturnObject getDCParkingMeter(string meternumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/newWebServices/LocationVerifier/getDCParkingMeter", ReplyAction="*")]
        System.Threading.Tasks.Task<BusinessCenter.Api.BusinessLocation.ReturnObject> getDCParkingMeterAsync(string meternumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/newWebServices/LocationVerifier/getDCParkingMeter2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        BusinessCenter.Api.BusinessLocation.ReturnObject getDCParkingMeter2(string meternumber, string f);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/newWebServices/LocationVerifier/getDCParkingMeter2", ReplyAction="*")]
        System.Threading.Tasks.Task<BusinessCenter.Api.BusinessLocation.ReturnObject> getDCParkingMeter2Async(string meternumber, string f);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/newWebServices/LocationVerifier/getDCStreetLight", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        BusinessCenter.Api.BusinessLocation.ReturnObject getDCStreetLight(string streetlightnumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/newWebServices/LocationVerifier/getDCStreetLight", ReplyAction="*")]
        System.Threading.Tasks.Task<BusinessCenter.Api.BusinessLocation.ReturnObject> getDCStreetLightAsync(string streetlightnumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/newWebServices/LocationVerifier/getDCStreetLight2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        BusinessCenter.Api.BusinessLocation.ReturnObject getDCStreetLight2(string streetlightnumber, string f);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/newWebServices/LocationVerifier/getDCStreetLight2", ReplyAction="*")]
        System.Threading.Tasks.Task<BusinessCenter.Api.BusinessLocation.ReturnObject> getDCStreetLight2Async(string streetlightnumber, string f);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/newWebServices/LocationVerifier/getStreetSegIDFromRoadwaySegID" +
            "", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        BusinessCenter.Api.BusinessLocation.ReturnObject getStreetSegIDFromRoadwaySegID(string roadwaysegid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/newWebServices/LocationVerifier/getStreetSegIDFromRoadwaySegID" +
            "", ReplyAction="*")]
        System.Threading.Tasks.Task<BusinessCenter.Api.BusinessLocation.ReturnObject> getStreetSegIDFromRoadwaySegIDAsync(string roadwaysegid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/newWebServices/LocationVerifier/getStreetSegIDFromRoadwaySegID" +
            "2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        BusinessCenter.Api.BusinessLocation.ReturnObject getStreetSegIDFromRoadwaySegID2(string roadwaysegid, string f);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/newWebServices/LocationVerifier/getStreetSegIDFromRoadwaySegID" +
            "2", ReplyAction="*")]
        System.Threading.Tasks.Task<BusinessCenter.Api.BusinessLocation.ReturnObject> getStreetSegIDFromRoadwaySegID2Async(string roadwaysegid, string f);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/newWebServices/LocationVerifier/getRoadwaySegIDFromStreetSegID" +
            "", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        BusinessCenter.Api.BusinessLocation.ReturnObject getRoadwaySegIDFromStreetSegID(string streetsegid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/newWebServices/LocationVerifier/getRoadwaySegIDFromStreetSegID" +
            "", ReplyAction="*")]
        System.Threading.Tasks.Task<BusinessCenter.Api.BusinessLocation.ReturnObject> getRoadwaySegIDFromStreetSegIDAsync(string streetsegid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/newWebServices/LocationVerifier/getRoadwaySegIDFromStreetSegID" +
            "2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        BusinessCenter.Api.BusinessLocation.ReturnObject getRoadwaySegIDFromStreetSegID2(string streetsegid, string f);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/newWebServices/LocationVerifier/getRoadwaySegIDFromStreetSegID" +
            "2", ReplyAction="*")]
        System.Threading.Tasks.Task<BusinessCenter.Api.BusinessLocation.ReturnObject> getRoadwaySegIDFromStreetSegID2Async(string streetsegid, string f);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/newWebServices/LocationVerifier")]
    public partial class ReturnObject : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string returnCodesField;
        
        private string detailsField;
        
        private System.Data.DataSet returnDatasetField;
        
        private System.Data.DataSet returnBlkAddrDatasetField;
        
        private System.Data.DataSet returnCDDataSetField;
        
        private string uNITField;
        
        private string uNITNUMBERField;
        
        private string sourceOperationField;
        
        private string processTimeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string returnCodes {
            get {
                return this.returnCodesField;
            }
            set {
                this.returnCodesField = value;
                this.RaisePropertyChanged("returnCodes");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string details {
            get {
                return this.detailsField;
            }
            set {
                this.detailsField = value;
                this.RaisePropertyChanged("details");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.Data.DataSet returnDataset {
            get {
                return this.returnDatasetField;
            }
            set {
                this.returnDatasetField = value;
                this.RaisePropertyChanged("returnDataset");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public System.Data.DataSet returnBlkAddrDataset {
            get {
                return this.returnBlkAddrDatasetField;
            }
            set {
                this.returnBlkAddrDatasetField = value;
                this.RaisePropertyChanged("returnBlkAddrDataset");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public System.Data.DataSet returnCDDataSet {
            get {
                return this.returnCDDataSetField;
            }
            set {
                this.returnCDDataSetField = value;
                this.RaisePropertyChanged("returnCDDataSet");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string UNIT {
            get {
                return this.uNITField;
            }
            set {
                this.uNITField = value;
                this.RaisePropertyChanged("UNIT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string UNITNUMBER {
            get {
                return this.uNITNUMBERField;
            }
            set {
                this.uNITNUMBERField = value;
                this.RaisePropertyChanged("UNITNUMBER");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string sourceOperation {
            get {
                return this.sourceOperationField;
            }
            set {
                this.sourceOperationField = value;
                this.RaisePropertyChanged("sourceOperation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string processTime {
            get {
                return this.processTimeField;
            }
            set {
                this.processTimeField = value;
                this.RaisePropertyChanged("processTime");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/newWebServices/LocationVerifier")]
    public partial class submitReturnObj : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string statusField;
        
        private string ticketNumField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ticketNum {
            get {
                return this.ticketNumField;
            }
            set {
                this.ticketNumField = value;
                this.RaisePropertyChanged("ticketNum");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface LocationVerifierSoapChannel : BusinessCenter.Api.BusinessLocation.LocationVerifierSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LocationVerifierSoapClient : System.ServiceModel.ClientBase<BusinessCenter.Api.BusinessLocation.LocationVerifierSoap>, BusinessCenter.Api.BusinessLocation.LocationVerifierSoap {
        
        public LocationVerifierSoapClient() {
        }
        
        public LocationVerifierSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LocationVerifierSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LocationVerifierSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LocationVerifierSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public BusinessCenter.Api.BusinessLocation.ReturnObject verifyDCAddressThrouString(string Address) {
            return base.Channel.verifyDCAddressThrouString(Address);
        }
        
        public System.Threading.Tasks.Task<BusinessCenter.Api.BusinessLocation.ReturnObject> verifyDCAddressThrouStringAsync(string Address) {
            return base.Channel.verifyDCAddressThrouStringAsync(Address);
        }
        
        public BusinessCenter.Api.BusinessLocation.ReturnObject verifyDCAddressThrouString2(string Address, string f) {
            return base.Channel.verifyDCAddressThrouString2(Address, f);
        }
        
        public System.Threading.Tasks.Task<BusinessCenter.Api.BusinessLocation.ReturnObject> verifyDCAddressThrouString2Async(string Address, string f) {
            return base.Channel.verifyDCAddressThrouString2Async(Address, f);
        }
        
        public BusinessCenter.Api.BusinessLocation.ReturnObject verifyDCAddressThrouComponents(string AddNumber, string AddNumberSuffix, string StName, string StType, string Quad) {
            return base.Channel.verifyDCAddressThrouComponents(AddNumber, AddNumberSuffix, StName, StType, Quad);
        }
        
        public System.Threading.Tasks.Task<BusinessCenter.Api.BusinessLocation.ReturnObject> verifyDCAddressThrouComponentsAsync(string AddNumber, string AddNumberSuffix, string StName, string StType, string Quad) {
            return base.Channel.verifyDCAddressThrouComponentsAsync(AddNumber, AddNumberSuffix, StName, StType, Quad);
        }
        
        public BusinessCenter.Api.BusinessLocation.ReturnObject verifyDCAddressThrouComponents2(string AddNumber, string AddNumberSuffix, string StName, string StType, string Quad, string f) {
            return base.Channel.verifyDCAddressThrouComponents2(AddNumber, AddNumberSuffix, StName, StType, Quad, f);
        }
        
        public System.Threading.Tasks.Task<BusinessCenter.Api.BusinessLocation.ReturnObject> verifyDCAddressThrouComponents2Async(string AddNumber, string AddNumberSuffix, string StName, string StType, string Quad, string f) {
            return base.Channel.verifyDCAddressThrouComponents2Async(AddNumber, AddNumberSuffix, StName, StType, Quad, f);
        }
        
        public BusinessCenter.Api.BusinessLocation.ReturnObject findOutsideLocation(string Location, string City, string State, string Zipcode) {
            return base.Channel.findOutsideLocation(Location, City, State, Zipcode);
        }
        
        public System.Threading.Tasks.Task<BusinessCenter.Api.BusinessLocation.ReturnObject> findOutsideLocationAsync(string Location, string City, string State, string Zipcode) {
            return base.Channel.findOutsideLocationAsync(Location, City, State, Zipcode);
        }
        
        public BusinessCenter.Api.BusinessLocation.ReturnObject findOutsideLocation2(string Location, string City, string State, string Zipcode, string f) {
            return base.Channel.findOutsideLocation2(Location, City, State, Zipcode, f);
        }
        
        public System.Threading.Tasks.Task<BusinessCenter.Api.BusinessLocation.ReturnObject> findOutsideLocation2Async(string Location, string City, string State, string Zipcode, string f) {
            return base.Channel.findOutsideLocation2Async(Location, City, State, Zipcode, f);
        }
        
        public BusinessCenter.Api.BusinessLocation.ReturnObject findInOutsideLocation(string Location, string City, string State, string Zipcode) {
            return base.Channel.findInOutsideLocation(Location, City, State, Zipcode);
        }
        
        public System.Threading.Tasks.Task<BusinessCenter.Api.BusinessLocation.ReturnObject> findInOutsideLocationAsync(string Location, string City, string State, string Zipcode) {
            return base.Channel.findInOutsideLocationAsync(Location, City, State, Zipcode);
        }
        
        public BusinessCenter.Api.BusinessLocation.ReturnObject findInOutsideLocation2(string Location, string City, string State, string Zipcode, string f) {
            return base.Channel.findInOutsideLocation2(Location, City, State, Zipcode, f);
        }
        
        public System.Threading.Tasks.Task<BusinessCenter.Api.BusinessLocation.ReturnObject> findInOutsideLocation2Async(string Location, string City, string State, string Zipcode, string f) {
            return base.Channel.findInOutsideLocation2Async(Location, City, State, Zipcode, f);
        }
        
        public BusinessCenter.Api.BusinessLocation.ReturnObject findDCInterThrouString(string Intersection) {
            return base.Channel.findDCInterThrouString(Intersection);
        }
        
        public System.Threading.Tasks.Task<BusinessCenter.Api.BusinessLocation.ReturnObject> findDCInterThrouStringAsync(string Intersection) {
            return base.Channel.findDCInterThrouStringAsync(Intersection);
        }
        
        public BusinessCenter.Api.BusinessLocation.ReturnObject findDCInterThrouString2(string Intersection, string f) {
            return base.Channel.findDCInterThrouString2(Intersection, f);
        }
        
        public System.Threading.Tasks.Task<BusinessCenter.Api.BusinessLocation.ReturnObject> findDCInterThrouString2Async(string Intersection, string f) {
            return base.Channel.findDCInterThrouString2Async(Intersection, f);
        }
        
        public BusinessCenter.Api.BusinessLocation.ReturnObject findDCInterThrouComponents(string crossstreet1, string crossstreet2) {
            return base.Channel.findDCInterThrouComponents(crossstreet1, crossstreet2);
        }
        
        public System.Threading.Tasks.Task<BusinessCenter.Api.BusinessLocation.ReturnObject> findDCInterThrouComponentsAsync(string crossstreet1, string crossstreet2) {
            return base.Channel.findDCInterThrouComponentsAsync(crossstreet1, crossstreet2);
        }
        
        public BusinessCenter.Api.BusinessLocation.ReturnObject findDCInterThrouComponents2(string crossstreet1, string crossstreet2, string f) {
            return base.Channel.findDCInterThrouComponents2(crossstreet1, crossstreet2, f);
        }
        
        public System.Threading.Tasks.Task<BusinessCenter.Api.BusinessLocation.ReturnObject> findDCInterThrouComponents2Async(string crossstreet1, string crossstreet2, string f) {
            return base.Channel.findDCInterThrouComponents2Async(crossstreet1, crossstreet2, f);
        }
        
        public BusinessCenter.Api.BusinessLocation.ReturnObject findDCInterThrouThreeComponents(string crossstreet1, string xtype, string crossstreet2) {
            return base.Channel.findDCInterThrouThreeComponents(crossstreet1, xtype, crossstreet2);
        }
        
        public System.Threading.Tasks.Task<BusinessCenter.Api.BusinessLocation.ReturnObject> findDCInterThrouThreeComponentsAsync(string crossstreet1, string xtype, string crossstreet2) {
            return base.Channel.findDCInterThrouThreeComponentsAsync(crossstreet1, xtype, crossstreet2);
        }
        
        public BusinessCenter.Api.BusinessLocation.ReturnObject findDCInterThrouThreeComponents2(string crossstreet1, string xtype, string crossstreet2, string f) {
            return base.Channel.findDCInterThrouThreeComponents2(crossstreet1, xtype, crossstreet2, f);
        }
        
        public System.Threading.Tasks.Task<BusinessCenter.Api.BusinessLocation.ReturnObject> findDCInterThrouThreeComponents2Async(string crossstreet1, string xtype, string crossstreet2, string f) {
            return base.Channel.findDCInterThrouThreeComponents2Async(crossstreet1, xtype, crossstreet2, f);
        }
        
        public BusinessCenter.Api.BusinessLocation.ReturnObject findDCBlkThrouString(string Block) {
            return base.Channel.findDCBlkThrouString(Block);
        }
        
        public System.Threading.Tasks.Task<BusinessCenter.Api.BusinessLocation.ReturnObject> findDCBlkThrouStringAsync(string Block) {
            return base.Channel.findDCBlkThrouStringAsync(Block);
        }
        
        public BusinessCenter.Api.BusinessLocation.ReturnObject findDCBlkThrouString2(string Block, string f) {
            return base.Channel.findDCBlkThrouString2(Block, f);
        }
        
        public System.Threading.Tasks.Task<BusinessCenter.Api.BusinessLocation.ReturnObject> findDCBlkThrouString2Async(string Block, string f) {
            return base.Channel.findDCBlkThrouString2Async(Block, f);
        }
        
        public BusinessCenter.Api.BusinessLocation.ReturnObject findDCBlkThrouComponents(string onstreet, string fromstreet, string tostreet) {
            return base.Channel.findDCBlkThrouComponents(onstreet, fromstreet, tostreet);
        }
        
        public System.Threading.Tasks.Task<BusinessCenter.Api.BusinessLocation.ReturnObject> findDCBlkThrouComponentsAsync(string onstreet, string fromstreet, string tostreet) {
            return base.Channel.findDCBlkThrouComponentsAsync(onstreet, fromstreet, tostreet);
        }
        
        public BusinessCenter.Api.BusinessLocation.ReturnObject findDCBlkThrouComponents2(string onstreet, string fromstreet, string tostreet, string f) {
            return base.Channel.findDCBlkThrouComponents2(onstreet, fromstreet, tostreet, f);
        }
        
        public System.Threading.Tasks.Task<BusinessCenter.Api.BusinessLocation.ReturnObject> findDCBlkThrouComponents2Async(string onstreet, string fromstreet, string tostreet, string f) {
            return base.Channel.findDCBlkThrouComponents2Async(onstreet, fromstreet, tostreet, f);
        }
        
        public BusinessCenter.Api.BusinessLocation.ReturnObject findAddFromSSL(string Square, string Suffix, string Lot) {
            return base.Channel.findAddFromSSL(Square, Suffix, Lot);
        }
        
        public System.Threading.Tasks.Task<BusinessCenter.Api.BusinessLocation.ReturnObject> findAddFromSSLAsync(string Square, string Suffix, string Lot) {
            return base.Channel.findAddFromSSLAsync(Square, Suffix, Lot);
        }
        
        public BusinessCenter.Api.BusinessLocation.ReturnObject findAddFromPlace(string Place) {
            return base.Channel.findAddFromPlace(Place);
        }
        
        public System.Threading.Tasks.Task<BusinessCenter.Api.BusinessLocation.ReturnObject> findAddFromPlaceAsync(string Place) {
            return base.Channel.findAddFromPlaceAsync(Place);
        }
        
        public BusinessCenter.Api.BusinessLocation.ReturnObject findAddFromPlace2(string Place, string f) {
            return base.Channel.findAddFromPlace2(Place, f);
        }
        
        public System.Threading.Tasks.Task<BusinessCenter.Api.BusinessLocation.ReturnObject> findAddFromPlace2Async(string Place, string f) {
            return base.Channel.findAddFromPlace2Async(Place, f);
        }
        
        public BusinessCenter.Api.BusinessLocation.ReturnObject findAID(string AID) {
            return base.Channel.findAID(AID);
        }
        
        public System.Threading.Tasks.Task<BusinessCenter.Api.BusinessLocation.ReturnObject> findAIDAsync(string AID) {
            return base.Channel.findAIDAsync(AID);
        }
        
        public BusinessCenter.Api.BusinessLocation.ReturnObject findAID2(string AID, string f) {
            return base.Channel.findAID2(AID, f);
        }
        
        public System.Threading.Tasks.Task<BusinessCenter.Api.BusinessLocation.ReturnObject> findAID2Async(string AID, string f) {
            return base.Channel.findAID2Async(AID, f);
        }
        
        public BusinessCenter.Api.BusinessLocation.ReturnObject findLocation(string str) {
            return base.Channel.findLocation(str);
        }
        
        public System.Threading.Tasks.Task<BusinessCenter.Api.BusinessLocation.ReturnObject> findLocationAsync(string str) {
            return base.Channel.findLocationAsync(str);
        }
        
        public BusinessCenter.Api.BusinessLocation.ReturnObject findLocation2(string str, string f) {
            return base.Channel.findLocation2(str, f);
        }
        
        public System.Threading.Tasks.Task<BusinessCenter.Api.BusinessLocation.ReturnObject> findLocation2Async(string str, string f) {
            return base.Channel.findLocation2Async(str, f);
        }
        
        public object[] findLocationBatch(string addr_base64, string addr_separator, string chunkSequnce_separator) {
            return base.Channel.findLocationBatch(addr_base64, addr_separator, chunkSequnce_separator);
        }
        
        public System.Threading.Tasks.Task<object[]> findLocationBatchAsync(string addr_base64, string addr_separator, string chunkSequnce_separator) {
            return base.Channel.findLocationBatchAsync(addr_base64, addr_separator, chunkSequnce_separator);
        }
        
        public object[] findLocationBatch2(string addr_base64, string addr_separator, string chunkSequnce_separator, string f) {
            return base.Channel.findLocationBatch2(addr_base64, addr_separator, chunkSequnce_separator, f);
        }
        
        public System.Threading.Tasks.Task<object[]> findLocationBatch2Async(string addr_base64, string addr_separator, string chunkSequnce_separator, string f) {
            return base.Channel.findLocationBatch2Async(addr_base64, addr_separator, chunkSequnce_separator, f);
        }
        
        public BusinessCenter.Api.BusinessLocation.ReturnObject findRdWySegIDFromMiniMARID(string MiniMARADDID) {
            return base.Channel.findRdWySegIDFromMiniMARID(MiniMARADDID);
        }
        
        public System.Threading.Tasks.Task<BusinessCenter.Api.BusinessLocation.ReturnObject> findRdWySegIDFromMiniMARIDAsync(string MiniMARADDID) {
            return base.Channel.findRdWySegIDFromMiniMARIDAsync(MiniMARADDID);
        }
        
        public BusinessCenter.Api.BusinessLocation.ReturnObject findRdWySegIDFromMiniMARID2(string MiniMARADDID, string f) {
            return base.Channel.findRdWySegIDFromMiniMARID2(MiniMARADDID, f);
        }
        
        public System.Threading.Tasks.Task<BusinessCenter.Api.BusinessLocation.ReturnObject> findRdWySegIDFromMiniMARID2Async(string MiniMARADDID, string f) {
            return base.Channel.findRdWySegIDFromMiniMARID2Async(MiniMARADDID, f);
        }
        
        public System.Data.DataSet findDCBlkFromIntersection(string crossstreet1, string crossstreet2) {
            return base.Channel.findDCBlkFromIntersection(crossstreet1, crossstreet2);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> findDCBlkFromIntersectionAsync(string crossstreet1, string crossstreet2) {
            return base.Channel.findDCBlkFromIntersectionAsync(crossstreet1, crossstreet2);
        }
        
        public System.Data.DataSet findDCBlkFromIntersection2(string crossstreet1, string crossstreet2, string f) {
            return base.Channel.findDCBlkFromIntersection2(crossstreet1, crossstreet2, f);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> findDCBlkFromIntersection2Async(string crossstreet1, string crossstreet2, string f) {
            return base.Channel.findDCBlkFromIntersection2Async(crossstreet1, crossstreet2, f);
        }
        
        public BusinessCenter.Api.BusinessLocation.ReturnObject findMARIDFromMiniMARID(string minimarid) {
            return base.Channel.findMARIDFromMiniMARID(minimarid);
        }
        
        public System.Threading.Tasks.Task<BusinessCenter.Api.BusinessLocation.ReturnObject> findMARIDFromMiniMARIDAsync(string minimarid) {
            return base.Channel.findMARIDFromMiniMARIDAsync(minimarid);
        }
        
        public BusinessCenter.Api.BusinessLocation.ReturnObject findMARIDFromMiniMARID2(string minimarid, string f) {
            return base.Channel.findMARIDFromMiniMARID2(minimarid, f);
        }
        
        public System.Threading.Tasks.Task<BusinessCenter.Api.BusinessLocation.ReturnObject> findMARIDFromMiniMARID2Async(string minimarid, string f) {
            return base.Channel.findMARIDFromMiniMARID2Async(minimarid, f);
        }
        
        public BusinessCenter.Api.BusinessLocation.ReturnObject findMiniMARIDFromMARID(string marid) {
            return base.Channel.findMiniMARIDFromMARID(marid);
        }
        
        public System.Threading.Tasks.Task<BusinessCenter.Api.BusinessLocation.ReturnObject> findMiniMARIDFromMARIDAsync(string marid) {
            return base.Channel.findMiniMARIDFromMARIDAsync(marid);
        }
        
        public BusinessCenter.Api.BusinessLocation.ReturnObject findMiniMARIDFromMARID2(string marid, string f) {
            return base.Channel.findMiniMARIDFromMARID2(marid, f);
        }
        
        public System.Threading.Tasks.Task<BusinessCenter.Api.BusinessLocation.ReturnObject> findMiniMARIDFromMARID2Async(string marid, string f) {
            return base.Channel.findMiniMARIDFromMARID2Async(marid, f);
        }
        
        public System.Data.DataSet reverseGeocoding(string x, string y) {
            return base.Channel.reverseGeocoding(x, y);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> reverseGeocodingAsync(string x, string y) {
            return base.Channel.reverseGeocodingAsync(x, y);
        }
        
        public System.Data.DataSet reverseGeocoding2(string x, string y, string f) {
            return base.Channel.reverseGeocoding2(x, y, f);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> reverseGeocoding2Async(string x, string y, string f) {
            return base.Channel.reverseGeocoding2Async(x, y, f);
        }
        
        public System.Data.DataSet reverseLatLngGeocoding(string lat, string lng) {
            return base.Channel.reverseLatLngGeocoding(lat, lng);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> reverseLatLngGeocodingAsync(string lat, string lng) {
            return base.Channel.reverseLatLngGeocodingAsync(lat, lng);
        }
        
        public System.Data.DataSet reverseLatLngGeocoding2(string lat, string lng, string f) {
            return base.Channel.reverseLatLngGeocoding2(lat, lng, f);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> reverseLatLngGeocoding2Async(string lat, string lng, string f) {
            return base.Channel.reverseLatLngGeocoding2Async(lat, lng, f);
        }
        
        public BusinessCenter.Api.BusinessLocation.submitReturnObj submitAddress(string address, string name, string agency, string phone, string email, string source, string comment, string withVerification) {
            return base.Channel.submitAddress(address, name, agency, phone, email, source, comment, withVerification);
        }
        
        public System.Threading.Tasks.Task<BusinessCenter.Api.BusinessLocation.submitReturnObj> submitAddressAsync(string address, string name, string agency, string phone, string email, string source, string comment, string withVerification) {
            return base.Channel.submitAddressAsync(address, name, agency, phone, email, source, comment, withVerification);
        }
        
        public BusinessCenter.Api.BusinessLocation.submitReturnObj submitAddress2(string address, string name, string agency, string phone, string email, string source, string comment, string withVerification, string f) {
            return base.Channel.submitAddress2(address, name, agency, phone, email, source, comment, withVerification, f);
        }
        
        public System.Threading.Tasks.Task<BusinessCenter.Api.BusinessLocation.submitReturnObj> submitAddress2Async(string address, string name, string agency, string phone, string email, string source, string comment, string withVerification, string f) {
            return base.Channel.submitAddress2Async(address, name, agency, phone, email, source, comment, withVerification, f);
        }
        
        public BusinessCenter.Api.BusinessLocation.ReturnObject findAddFromSSL_new(string Square, string Suffix, string Lot) {
            return base.Channel.findAddFromSSL_new(Square, Suffix, Lot);
        }
        
        public System.Threading.Tasks.Task<BusinessCenter.Api.BusinessLocation.ReturnObject> findAddFromSSL_newAsync(string Square, string Suffix, string Lot) {
            return base.Channel.findAddFromSSL_newAsync(Square, Suffix, Lot);
        }
        
        public BusinessCenter.Api.BusinessLocation.ReturnObject findAddFromSSL_new2(string Square, string Suffix, string Lot, string f) {
            return base.Channel.findAddFromSSL_new2(Square, Suffix, Lot, f);
        }
        
        public System.Threading.Tasks.Task<BusinessCenter.Api.BusinessLocation.ReturnObject> findAddFromSSL_new2Async(string Square, string Suffix, string Lot, string f) {
            return base.Channel.findAddFromSSL_new2Async(Square, Suffix, Lot, f);
        }
        
        public BusinessCenter.Api.BusinessLocation.ReturnObject findAddFromSSL2(string Square, string Suffix, string Lot, string f) {
            return base.Channel.findAddFromSSL2(Square, Suffix, Lot, f);
        }
        
        public System.Threading.Tasks.Task<BusinessCenter.Api.BusinessLocation.ReturnObject> findAddFromSSL2Async(string Square, string Suffix, string Lot, string f) {
            return base.Channel.findAddFromSSL2Async(Square, Suffix, Lot, f);
        }
        
        public BusinessCenter.Api.BusinessLocation.ReturnObject findSSLFromAID(string AID) {
            return base.Channel.findSSLFromAID(AID);
        }
        
        public System.Threading.Tasks.Task<BusinessCenter.Api.BusinessLocation.ReturnObject> findSSLFromAIDAsync(string AID) {
            return base.Channel.findSSLFromAIDAsync(AID);
        }
        
        public BusinessCenter.Api.BusinessLocation.ReturnObject findSSLFromAID2(string AID, string f) {
            return base.Channel.findSSLFromAID2(AID, f);
        }
        
        public System.Threading.Tasks.Task<BusinessCenter.Api.BusinessLocation.ReturnObject> findSSLFromAID2Async(string AID, string f) {
            return base.Channel.findSSLFromAID2Async(AID, f);
        }
        
        public BusinessCenter.Api.BusinessLocation.ReturnObject FindCondoUnitFromAID(string AID) {
            return base.Channel.FindCondoUnitFromAID(AID);
        }
        
        public System.Threading.Tasks.Task<BusinessCenter.Api.BusinessLocation.ReturnObject> FindCondoUnitFromAIDAsync(string AID) {
            return base.Channel.FindCondoUnitFromAIDAsync(AID);
        }
        
        public BusinessCenter.Api.BusinessLocation.ReturnObject FindCondoUnitFromAID2(string AID, string f) {
            return base.Channel.FindCondoUnitFromAID2(AID, f);
        }
        
        public System.Threading.Tasks.Task<BusinessCenter.Api.BusinessLocation.ReturnObject> FindCondoUnitFromAID2Async(string AID, string f) {
            return base.Channel.FindCondoUnitFromAID2Async(AID, f);
        }
        
        public BusinessCenter.Api.BusinessLocation.ReturnObject findAliasFromAID(string AID) {
            return base.Channel.findAliasFromAID(AID);
        }
        
        public System.Threading.Tasks.Task<BusinessCenter.Api.BusinessLocation.ReturnObject> findAliasFromAIDAsync(string AID) {
            return base.Channel.findAliasFromAIDAsync(AID);
        }
        
        public BusinessCenter.Api.BusinessLocation.ReturnObject findAliasFromAID2(string AID, string f) {
            return base.Channel.findAliasFromAID2(AID, f);
        }
        
        public System.Threading.Tasks.Task<BusinessCenter.Api.BusinessLocation.ReturnObject> findAliasFromAID2Async(string AID, string f) {
            return base.Channel.findAliasFromAID2Async(AID, f);
        }
        
        public BusinessCenter.Api.BusinessLocation.ReturnObject findOwnerFromSSL(string Square, string Suffix, string Lot) {
            return base.Channel.findOwnerFromSSL(Square, Suffix, Lot);
        }
        
        public System.Threading.Tasks.Task<BusinessCenter.Api.BusinessLocation.ReturnObject> findOwnerFromSSLAsync(string Square, string Suffix, string Lot) {
            return base.Channel.findOwnerFromSSLAsync(Square, Suffix, Lot);
        }
        
        public BusinessCenter.Api.BusinessLocation.ReturnObject findOwnerFromSSL2(string Square, string Suffix, string Lot, string f) {
            return base.Channel.findOwnerFromSSL2(Square, Suffix, Lot, f);
        }
        
        public System.Threading.Tasks.Task<BusinessCenter.Api.BusinessLocation.ReturnObject> findOwnerFromSSL2Async(string Square, string Suffix, string Lot, string f) {
            return base.Channel.findOwnerFromSSL2Async(Square, Suffix, Lot, f);
        }
        
        public BusinessCenter.Api.BusinessLocation.ReturnObject findSSLFromSquareSuffix(string Square, string Suffix) {
            return base.Channel.findSSLFromSquareSuffix(Square, Suffix);
        }
        
        public System.Threading.Tasks.Task<BusinessCenter.Api.BusinessLocation.ReturnObject> findSSLFromSquareSuffixAsync(string Square, string Suffix) {
            return base.Channel.findSSLFromSquareSuffixAsync(Square, Suffix);
        }
        
        public BusinessCenter.Api.BusinessLocation.ReturnObject findSSLFromSquareSuffix2(string Square, string Suffix, string f) {
            return base.Channel.findSSLFromSquareSuffix2(Square, Suffix, f);
        }
        
        public System.Threading.Tasks.Task<BusinessCenter.Api.BusinessLocation.ReturnObject> findSSLFromSquareSuffix2Async(string Square, string Suffix, string f) {
            return base.Channel.findSSLFromSquareSuffix2Async(Square, Suffix, f);
        }
        
        public BusinessCenter.Api.BusinessLocation.ReturnObject FindUnitFromAID(string AID) {
            return base.Channel.FindUnitFromAID(AID);
        }
        
        public System.Threading.Tasks.Task<BusinessCenter.Api.BusinessLocation.ReturnObject> FindUnitFromAIDAsync(string AID) {
            return base.Channel.FindUnitFromAIDAsync(AID);
        }
        
        public BusinessCenter.Api.BusinessLocation.ReturnObject FindUnitFromAID2(string AID, string f) {
            return base.Channel.FindUnitFromAID2(AID, f);
        }
        
        public System.Threading.Tasks.Task<BusinessCenter.Api.BusinessLocation.ReturnObject> FindUnitFromAID2Async(string AID, string f) {
            return base.Channel.FindUnitFromAID2Async(AID, f);
        }
        
        public BusinessCenter.Api.BusinessLocation.ReturnObject findROW(string roadwaysegid) {
            return base.Channel.findROW(roadwaysegid);
        }
        
        public System.Threading.Tasks.Task<BusinessCenter.Api.BusinessLocation.ReturnObject> findROWAsync(string roadwaysegid) {
            return base.Channel.findROWAsync(roadwaysegid);
        }
        
        public BusinessCenter.Api.BusinessLocation.ReturnObject findROW2(string roadwaysegid, string f) {
            return base.Channel.findROW2(roadwaysegid, f);
        }
        
        public System.Threading.Tasks.Task<BusinessCenter.Api.BusinessLocation.ReturnObject> findROW2Async(string roadwaysegid, string f) {
            return base.Channel.findROW2Async(roadwaysegid, f);
        }
        
        public BusinessCenter.Api.BusinessLocation.ReturnObject getDCStreetNames(string quad, string initialetters) {
            return base.Channel.getDCStreetNames(quad, initialetters);
        }
        
        public System.Threading.Tasks.Task<BusinessCenter.Api.BusinessLocation.ReturnObject> getDCStreetNamesAsync(string quad, string initialetters) {
            return base.Channel.getDCStreetNamesAsync(quad, initialetters);
        }
        
        public BusinessCenter.Api.BusinessLocation.ReturnObject getDCStreetNames2(string quad, string initialetters, string f) {
            return base.Channel.getDCStreetNames2(quad, initialetters, f);
        }
        
        public System.Threading.Tasks.Task<BusinessCenter.Api.BusinessLocation.ReturnObject> getDCStreetNames2Async(string quad, string initialetters, string f) {
            return base.Channel.getDCStreetNames2Async(quad, initialetters, f);
        }
        
        public BusinessCenter.Api.BusinessLocation.ReturnObject getDCAddresses(string initialetters) {
            return base.Channel.getDCAddresses(initialetters);
        }
        
        public System.Threading.Tasks.Task<BusinessCenter.Api.BusinessLocation.ReturnObject> getDCAddressesAsync(string initialetters) {
            return base.Channel.getDCAddressesAsync(initialetters);
        }
        
        public BusinessCenter.Api.BusinessLocation.ReturnObject getDCAddresses2(string initialetters, string f) {
            return base.Channel.getDCAddresses2(initialetters, f);
        }
        
        public System.Threading.Tasks.Task<BusinessCenter.Api.BusinessLocation.ReturnObject> getDCAddresses2Async(string initialetters, string f) {
            return base.Channel.getDCAddresses2Async(initialetters, f);
        }
        
        public BusinessCenter.Api.BusinessLocation.ReturnObject getDCParkingMeter(string meternumber) {
            return base.Channel.getDCParkingMeter(meternumber);
        }
        
        public System.Threading.Tasks.Task<BusinessCenter.Api.BusinessLocation.ReturnObject> getDCParkingMeterAsync(string meternumber) {
            return base.Channel.getDCParkingMeterAsync(meternumber);
        }
        
        public BusinessCenter.Api.BusinessLocation.ReturnObject getDCParkingMeter2(string meternumber, string f) {
            return base.Channel.getDCParkingMeter2(meternumber, f);
        }
        
        public System.Threading.Tasks.Task<BusinessCenter.Api.BusinessLocation.ReturnObject> getDCParkingMeter2Async(string meternumber, string f) {
            return base.Channel.getDCParkingMeter2Async(meternumber, f);
        }
        
        public BusinessCenter.Api.BusinessLocation.ReturnObject getDCStreetLight(string streetlightnumber) {
            return base.Channel.getDCStreetLight(streetlightnumber);
        }
        
        public System.Threading.Tasks.Task<BusinessCenter.Api.BusinessLocation.ReturnObject> getDCStreetLightAsync(string streetlightnumber) {
            return base.Channel.getDCStreetLightAsync(streetlightnumber);
        }
        
        public BusinessCenter.Api.BusinessLocation.ReturnObject getDCStreetLight2(string streetlightnumber, string f) {
            return base.Channel.getDCStreetLight2(streetlightnumber, f);
        }
        
        public System.Threading.Tasks.Task<BusinessCenter.Api.BusinessLocation.ReturnObject> getDCStreetLight2Async(string streetlightnumber, string f) {
            return base.Channel.getDCStreetLight2Async(streetlightnumber, f);
        }
        
        public BusinessCenter.Api.BusinessLocation.ReturnObject getStreetSegIDFromRoadwaySegID(string roadwaysegid) {
            return base.Channel.getStreetSegIDFromRoadwaySegID(roadwaysegid);
        }
        
        public System.Threading.Tasks.Task<BusinessCenter.Api.BusinessLocation.ReturnObject> getStreetSegIDFromRoadwaySegIDAsync(string roadwaysegid) {
            return base.Channel.getStreetSegIDFromRoadwaySegIDAsync(roadwaysegid);
        }
        
        public BusinessCenter.Api.BusinessLocation.ReturnObject getStreetSegIDFromRoadwaySegID2(string roadwaysegid, string f) {
            return base.Channel.getStreetSegIDFromRoadwaySegID2(roadwaysegid, f);
        }
        
        public System.Threading.Tasks.Task<BusinessCenter.Api.BusinessLocation.ReturnObject> getStreetSegIDFromRoadwaySegID2Async(string roadwaysegid, string f) {
            return base.Channel.getStreetSegIDFromRoadwaySegID2Async(roadwaysegid, f);
        }
        
        public BusinessCenter.Api.BusinessLocation.ReturnObject getRoadwaySegIDFromStreetSegID(string streetsegid) {
            return base.Channel.getRoadwaySegIDFromStreetSegID(streetsegid);
        }
        
        public System.Threading.Tasks.Task<BusinessCenter.Api.BusinessLocation.ReturnObject> getRoadwaySegIDFromStreetSegIDAsync(string streetsegid) {
            return base.Channel.getRoadwaySegIDFromStreetSegIDAsync(streetsegid);
        }
        
        public BusinessCenter.Api.BusinessLocation.ReturnObject getRoadwaySegIDFromStreetSegID2(string streetsegid, string f) {
            return base.Channel.getRoadwaySegIDFromStreetSegID2(streetsegid, f);
        }
        
        public System.Threading.Tasks.Task<BusinessCenter.Api.BusinessLocation.ReturnObject> getRoadwaySegIDFromStreetSegID2Async(string streetsegid, string f) {
            return base.Channel.getRoadwaySegIDFromStreetSegID2Async(streetsegid, f);
        }
    }
}
