//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessCenter.Data
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class AuditRecord
    {
        [Key]
        public long Id { get; set; }
        public string AuditId { get; set; }
        public string SessionId { get; set; }
        public string IpAddress { get; set; }
        public string UserName { get; set; }
        public string UrlAccessed { get; set; }
        public Nullable<System.DateTime> TimeAccessed { get; set; }
        public string Data { get; set; }
    }
}
