//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessCenter.Data
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class BblLicenseView4
    {
        [Key]
        public int APPID { get; set; }
        public string Application_License_No_ { get; set; }
        public string FileName { get; set; }
        public string SubmissionFileLocation { get; set; }
       
        public string DocumentSubmissionType { get; set; }
        public string CategoryName { get; set; }
        public Nullable<int> MasterCategoryDocId { get; set; }
        public string SubmissionType { get; set; }
        public string Agency { get; set; }
        public string Agency_FullName { get; set; }
        public string Div { get; set; }
        public string DivisionFullName { get; set; }
        public string SupportingDocuments { get; set; }
        public string ShortDocName { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public Nullable<System.DateTime> UpDated_Date { get; set; }
    }
}
