//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessCenter.Data
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class BblLicenseView2
    {
        [Key]
        public string Application { get; set; }
        public string Primary_Category { get; set; }
        public string Class { get; set; }
        public string Pri__Units { get; set; }
        public string Pri__Units_Description { get; set; }
        public string Pri__Units_2 { get; set; }
        public string Pri__Units_Description_2 { get; set; }
        public string Secondary_Category { get; set; }
        public string Sec__Units { get; set; }
        public string Sec__Units_Description { get; set; }
        public string SubCategoryName { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public Nullable<System.DateTime> UpDated_Date { get; set; }
    }
}
