//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessCenter.Data
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class BblLicenseView
    {
        [Key]
        public string Application_Unique_ID { get; set; }
        public string Full_Name { get; set; }
        public string Applicant_Name { get; set; }
        public string Online_App_License_Status { get; set; }       
        public string Application_License_No_ { get; set; }
        public string Application_Type { get; set; }
        public string App_Type { get; set; }
        public Nullable<int> License_Period { get; set; }
        public Nullable<decimal> ApplicationFee { get; set; }
        public Nullable<decimal> EndorsementFee { get; set; }
        public Nullable<decimal> LicenseFee { get; set; }
        public Nullable<decimal> RAOFee { get; set; }
        public Nullable<decimal> ESFFee { get; set; }
        public string EHOP_Fees { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public string Payment_Transaction_ID { get; set; }
        public string Payment_Transaction_Date { get; set; }
        public string CH_Self_Certificate_Signature { get; set; }
        public Nullable<System.DateTime> CH_Self_Certificate_Date { get; set; }
        public string CH_Self_Certificate_Type { get; set; }
        public string Self_Certificate__One_Family_ { get; set; }
        public string Certificate_of_Occupancy_Number { get; set; }
        public string Home_Occupation_Number { get; set; }
        public string EHOP_Number { get; set; }
        public Nullable<System.DateTime> EHOP_Issue_Date { get; set; }
        public string EHOP_Attested_By { get; set; }
        public string EHOP_Occupation_Type { get; set; }
        public string EHOP_Issuance_Status { get; set; }
        public string First_Name { get; set; }
        public string Middle_Name { get; set; }
        public string Last_Name { get; set; }
        public string Organization_Name { get; set; }
        public string Full_Address_Line_1 { get; set; }
        public string Address_Line_2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip_Code { get; set; }
        public string Country_Region { get; set; }
        public string Email { get; set; }
        public string Business_Organization___ { get; set; }
        public string Trade_Name__If_applicable_ { get; set; }
        public string Tax_ID_Number { get; set; }
        public string FEIN_SSN { get; set; }
        public string Prim_Street_Number { get; set; }
        public string Prim_Street_Name { get; set; }
        public string StreetType { get; set; }
        public string Quadrant { get; set; }
        public string Unit_Type___ { get; set; }
        public string Suite_Unit_Number { get; set; }
        public string PCity { get; set; }
        public string PState { get; set; }
        public string Country__ { get; set; }
        public string PZip { get; set; }
        public string Phone { get; set; }
        public string Premise_Address_Verified { get; set; }
        public string Parcel_Premise_Suffix { get; set; }
        public string Parcel_Premise_Ward { get; set; }
        public string Parcel_Premise_ANC { get; set; }
        public string Parcel_Premise_Zone { get; set; }
        public string Parcel_Premise_SSL { get; set; }
        public string Billing_Org_Buss__Name { get; set; }
        public string Billing_ContactFirstName { get; set; }
        public string Billing_ContactMiddleName { get; set; }
        public string Billing_ContactLastName { get; set; }
        public string Billing_Address_1 { get; set; }
        public string Billing_Address_2_ { get; set; }
        public string Billing_Address_3 { get; set; }
        public string Billing_City { get; set; }
        public string Billing_State { get; set; }
        public string Billing_Country___ { get; set; }
        public string Billing_Zip { get; set; }
        public string Billing_Phone { get; set; }
        public string Billing_Email { get; set; }
        public string Agent_Org_Buss__Name { get; set; }
        public string Contact_First_Name { get; set; }
        public string Contact_Middle_Name { get; set; }
        public string Contact_Last_Name { get; set; }
        public string Street_Address { get; set; }
        public string Address_Line__2_ { get; set; }
        public string ContactAgent_City { get; set; }
        public string ContactAgent_State { get; set; }
        public string ContactAgent_Country { get; set; }
        public string ContactAgent_ZipCode { get; set; }
        public string Corp_Telephone { get; set; }
        public string ContactAgent_Email { get; set; }
        public string FileNumber { get; set; }
        public string Company_Name { get; set; }
        public string Employee_Name { get; set; }
        public string Company_Buss__Lic_Number { get; set; }
        public Nullable<System.DateTime> Date_of_Birth { get; set; }
        public string Place_of_Birth { get; set; }
        public string Height { get; set; }
        public string Weight { get; set; }
        public string Hair_Color { get; set; }
        public string Eyes_Color { get; set; }
        public string Drivers_License { get; set; }
        public string State_of_License { get; set; }
        public Nullable<System.DateTime> License_Expiration_Date { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public Nullable<System.DateTime> UpDated_Date { get; set; }
    }
}
