//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessCenter.Data
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class DCBC_ENTITY_Cof_O
    {
        [Key]
        public int DCBC_ENTITY_ID { get; set; }
      
        public bool REC_STATUS { get; set; }
      
        public System.DateTime LAST_UPDATE { get; set; }
      
        public string DCBC_ENTITY_SOURCE { get; set; }
       
        public System.DateTime As_of_Date { get; set; }
        public string B1_APP_TYPE_ALIAS { get; set; }
        public string b1_Alt_ID { get; set; }
        public string B1_APPL_STATUS { get; set; }
        
        public string DCBC_Status { get; set; }
        public Nullable<System.DateTime> B1_APPL_STATUS_DATE { get; set; }
        public Nullable<int> B1_HSE_NBR_START { get; set; }
        public Nullable<int> B1_HSE_NBR_END { get; set; }
        public string B1_HSE_FRAC_NBR_START { get; set; }
        public string B1_UNIT_START { get; set; }
        public string B1_STR_NAME { get; set; }
        public string B1_STR_SUFFIX { get; set; }
        public string B1_STR_SUFFIX_DIR { get; set; }
        public string B1_SITUS_CITY { get; set; }
        public string B1_SITUS_STATE { get; set; }
        public string B1_SITUS_ZIP { get; set; }
        public string B1_SITUS_NBRHD { get; set; }
        public string Zoning_Use { get; set; }
        public string Medical_Marijuana_Dispensary { get; set; }
        public string SD_APP_DES { get; set; }
        public Nullable<System.DateTime> Status_DATE { get; set; }
       
        public System.DateTime REC_DATE { get; set; }
    }
}
