//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessCenter.Data
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class DCBC_ENTITY_ABRA
    {
        [Key]
        public int DCBC_ENTITY_ID { get; set; }
        
        public bool REC_STATUS { get; set; }
      
        public System.DateTime LAST_UPDATE { get; set; }
      
        public string DCBC_ENTITY_SOURCE { get; set; }
      
        public string Serv_Prov_Code { get; set; }
       
        public string B1_PER_GROUP { get; set; }
      
        public string B1_PER_TYPE { get; set; }
      
        public string B1_PER_CATEGORY { get; set; }
        public string B1_APP_TYPE_ALIAS { get; set; }
        public string APP_STATUS_GROUP_CODE { get; set; }
        public string B1_SPECIAL_TEXT { get; set; }
        public string License_Number { get; set; }
        public Nullable<long> B1_TRACKING_NBR { get; set; }
        public string License_Status { get; set; }
        public Nullable<System.DateTime> B1_APPL_STATUS_DATE { get; set; }
        public string B1_CHECKBOX_TYPE { get; set; }
        public string License_Expiration_Date { get; set; }
        public string Valid_Thru_Date { get; set; }
        public string Posting_Date { get; set; }
        public string Class_Type { get; set; }
        public string Class_Type_AttrValue { get; set; }
        public string Establishment_Type { get; set; }
        public string Applicant_FNAME { get; set; }
        public string Applicant_MNAME { get; set; }
        public string Applicant_LNAME { get; set; }
        public string Applicant_FULL_NAME { get; set; }
        public string Applicant_RELATION { get; set; }
        public string Applicant_BUSINESS_NAME { get; set; }
        public string Solicitor_FNAME { get; set; }
        public string Solicitor_MNAME { get; set; }
        public string Solicitor_LNAME { get; set; }
        public string Solicitor_FULL_NAME { get; set; }
        public string Solicitor_RELATION { get; set; }
        public string Solicitor_BUSINESS_NAME { get; set; }
        public string Solicitor_ADDR1 { get; set; }
        public string Solicitor_ADDR2 { get; set; }
        public string Solicitor_ADDR3 { get; set; }
        public string Solicitor_CITY { get; set; }
        public string Solicitor_STATE { get; set; }
        public string Solicitor_ZIP { get; set; }
        public string Manager_FNAME { get; set; }
        public string Manager_MNAME { get; set; }
        public string Manager_LNAME { get; set; }
        public string Manager_FULL_NAME { get; set; }
        public string Manager_RELATION { get; set; }
        public string Manager_BUSINESS_NAME { get; set; }
        public string Manager_ADDR1 { get; set; }
        public string Manager_ADDR2 { get; set; }
        public string Manager_ADDR3 { get; set; }
        public string Manager_CITY { get; set; }
        public string Manager_STATE { get; set; }
        public string Manager_ZIP { get; set; }
        public string B1_PRIMARY_ADDR_FLG { get; set; }
        public Nullable<int> B1_HSE_NBR_START { get; set; }
        public Nullable<int> B1_HSE_NBR_END { get; set; }
        public string B1_HSE_FRAC_NBR_START { get; set; }
        public string B1_HSE_FRAC_NBR_END { get; set; }
        public string B1_UNIT_START { get; set; }
        public string B1_STR_NAME { get; set; }
        public string B1_STR_SUFFIX { get; set; }
        public string B1_STR_SUFFIX_DIR { get; set; }
        public string B1_SITUS_CITY { get; set; }
        public string B1_SITUS_STATE { get; set; }
        public string B1_SITUS_ZIP { get; set; }
    }
}
