//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessCenter.Data
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class DCBC_ENTITY_CORP
    {
        [Key]
        public int DCBC_ENTITY_ID { get; set; }
       
        public bool REC_STATUS { get; set; }
      
        public System.DateTime LAST_UPDATE { get; set; }
       
        public string DCBC_ENTITY_SOURCE { get; set; }
       
        public System.DateTime REC_DATE { get; set; }
        public Nullable<int> BizEntityId { get; set; }
        public string FileNumber { get; set; }
        public string EntityStatus { get; set; }
        public Nullable<System.DateTime> EntityStatusDate { get; set; }
        public string Locale { get; set; }
        public string Qualifier { get; set; }
        public string ModelType { get; set; }
        public string BusinessName { get; set; }
        public string Suffix { get; set; }
        public string BusniessAddressLine1 { get; set; }
        public string BusniessAddressLine2 { get; set; }
        public string BusniessAddressLine3 { get; set; }
        public string BusniessAddressLine4 { get; set; }
        public string BusinessCity { get; set; }
        public string BusinessState { get; set; }
        public string ZipCode { get; set; }
        public string BusinessCountry { get; set; }
        public string RA_Name { get; set; }
        public string RA_Address1 { get; set; }
        public string RA_Address2 { get; set; }
        public string RA_Address3 { get; set; }
        public string RA_Address4 { get; set; }
        public string RA_City { get; set; }
        public string RA_State { get; set; }
        public string RA_ZipCode { get; set; }
        public string RA_Email { get; set; }
        public Nullable<System.DateTime> EffectiveDate { get; set; }
        public string ForeignDateOfOrganization { get; set; }
        public string NextReportYear { get; set; }
        public string ModelType_ORIGINAL { get; set; }
    }
}
