//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessCenter.Data
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class DCBC_ENTITY_OPLA
    {
        [Key]
        public int DCBC_ENTITY_ID { get; set; }
     
        public bool REC_STATUS { get; set; }
     
        public System.DateTime LAST_UPDATE { get; set; }
      
        public string DCBC_ENTITY_SOURCE { get; set; }
        public string BOARD_ABBREVIATION { get; set; }
        public string LICENSE_PREFIX { get; set; }
        public string LICENSE_NUMBER { get; set; }
        public Nullable<System.DateTime> LICENSE_ISSUE_DATE { get; set; }
        public Nullable<System.DateTime> LICENSE_EXPIRATION_DATE { get; set; }
        public string LICENSE_STATUS_CODE { get; set; }
        public string Licensee_Name_1 { get; set; }
        public string Licensee_Name_2 { get; set; }
        public string Licensee_Name_3 { get; set; }
        public string Licensee_Name_4 { get; set; }
        public string BUSINESS_ADDRESS { get; set; }
        public string BUSINESS_CITY { get; set; }
        public string BUSINESS_STATE { get; set; }
        public string BUSINESS_ZIP { get; set; }
        public string BUSINESS_PHONE { get; set; }
        public string HOME_ADDRESS { get; set; }
        public string HOME_CITY { get; set; }
        public string HOME_STATE { get; set; }
        public string HOME_ZIP { get; set; }
        public string HOME_PHONE { get; set; }
        public string Preferred_Address_Ind { get; set; }
        public string EMPLOYER_LICENSE_PREFIX1 { get; set; }
        public string EMPLOYER_LICENSE_NUMBER { get; set; }
        public string Organization_EMPLOYER_NAME { get; set; }
        public Nullable<System.DateTime> EMPLOYER_LICENSE_ISSUE_DATE { get; set; }
        public Nullable<System.DateTime> EMPLOYER_LICENSE_EXPIRATION_DATE { get; set; }
        public string EMPLOYER_LICENSE_STATUS_CODE { get; set; }
        public string EMPLOYER_ADDRESS { get; set; }
        public string EMPLOYER_CITY { get; set; }
        public string EMPLOYER_STATE { get; set; }
        public string EMPLOYER_ZIP { get; set; }
        public string EMPLOYER_PHONE { get; set; }
        public string FULL_NAME { get; set; }
        public string OPLA_LICENSE_CATEGORY { get; set; }
        public string OPLA_SOURCE { get; set; }
       
        public System.DateTime REC_DATE { get; set; }
        public string License_Board { get; set; }
        public string License_Type { get; set; }
    }
}
