//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessCenter.Data
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    public partial class DCBC_ENTITY_BBL_Renewal_Invoice
    {
        public Nullable<System.DateTime> As_of_Date { get; set; }
        [Key, Column(Order = 1)]
        public string SERV_PROV_CODE { get; set; }
        [Key, Column(Order = 2)]
        public string B1_PER_ID1 { get; set; }
        [Key, Column(Order = 3)]
        public string B1_PER_ID2 { get; set; }
        [Key, Column(Order = 4)]
        public string B1_PER_ID3 { get; set; }
        [Key, Column(Order = 5)]
        public string B1_PER_GROUP { get; set; }
        [Key, Column(Order = 6)]
        public string B1_PER_TYPE { get; set; }
        [Key, Column(Order = 7)]
        public string B1_PER_SUB_TYPE { get; set; }
        [Key, Column(Order = 8)]
        public string B1_PER_CATEGORY { get; set; }
        public string B1_APP_TYPE_ALIAS { get; set; }
        [Key, Column(Order = 9)]
        public string b1_Alt_ID { get; set; }
        [Key, Column(Order = 10)]
        public string GF_DES { get; set; }
        [Key, Column(Order = 11)]
        public Nullable<decimal> GF_FEE { get; set; }
        public Nullable<decimal> GF_UNIT { get; set; }
    }
}
