//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessCenter.Data
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class DCBC_ENTITY_CBE
    {
        [Key]
        public int DCBC_ENTITY_ID { get; set; }
       
        public bool REC_STATUS { get; set; }
       
        public System.DateTime LAST_UPDATE { get; set; }
      
        public string DCBC_ENTITY_SOURCE { get; set; }
        public Nullable<int> LsdbeID { get; set; }
        public Nullable<int> CompanyID { get; set; }
      
        public string BusinessName { get; set; }
        public string BusinessAddress { get; set; }
        public string BusinessAddressShort { get; set; }
        public string BusinessPhone { get; set; }
        public string BusinessFax { get; set; }
        public string BusinessEmail { get; set; }
        public string GIS_Ward { get; set; }
        public Nullable<System.DateTime> CertificationExpiry { get; set; }
        public Nullable<int> NIGPAppID { get; set; }
        public Nullable<int> TradeDivAppID { get; set; }
        public Nullable<int> BAPAppID { get; set; }
        public string BusinessStructure { get; set; }
        public Nullable<System.DateTime> IncorporationDate { get; set; }
      
        public string BusinessDescription { get; set; }
        public string BusinessContact { get; set; }
        public string LSDBE_Number { get; set; }
        public Nullable<int> RefPoints { get; set; }
        public string RefPointsDesc { get; set; }
        public string BusinessAddress1 { get; set; }
        public string BusinessAddress2 { get; set; }
        public string BusinessCity { get; set; }
        public string BusinessState { get; set; }
        public string BusinessZip1 { get; set; }
        public string BusinessZip2 { get; set; }
        public string LSDBEBusinessOptions { get; set; }
        public string BusinessWebsite { get; set; }
        public Nullable<int> Lsdbe_PersonAppID { get; set; }
        public string MailingAddress { get; set; }
        public string PublicContact { get; set; }
    }
}
