//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessCenter.Data
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class FixFee
    {
        public Nullable<decimal> ApplicationFee { get; set; }
        public Nullable<decimal> EndorsementFee { get; set; }
        public Nullable<decimal> TradeRegFee { get; set; }
        public Nullable<decimal> RAOFee { get; set; }
        public Nullable<decimal> eHOPFee { get; set; }
        [Key]
        public int Id { get; set; }
    }
}
