//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessCenter.Data
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class KeywordMaster
    {
        [Key]
        public long KeyId { get; set; }
        public string Keywords { get; set; }
        public string TypeID { get; set; }
        public string SearchCriteria { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
