//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessCenter.Data
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class Lookup_BusinessStructure
    {
        [Key]
        public int LookUpBusinessStructureId { get; set; }
        public string BusinessStructure { get; set; }
        public Nullable<bool> IsManualAddress { get; set; }
    }
}
