//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessCenter.Data
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class MailTemplate
    {
        [Key]
        public string EmailTemplateId { get; set; }
        public string Type { get; set; }
        public string Subject { get; set; }
        public Nullable<int> MailSentFailCount { get; set; }
        public string MailContent { get; set; }
        public Nullable<bool> IsMailSent { get; set; }
        public Nullable<System.DateTime> MailCreatedDate { get; set; }
        public Nullable<System.DateTime> MailSentDate { get; set; }
        public string UserId { get; set; }
        public string Custom_Application_Id { get; set; }
    }
}
