//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessCenter.Data
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class MasterSubCategory
    {
        [Key]
        public string SubCatID { get; set; }
        public string SubCategoryName { get; set; }
        public string CustomCategoryName { get; set; }
        public Nullable<bool> Status { get; set; }
    }
}
