//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessCenter.Data
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class MasterCategoryQuestion
    {
        [Key]
        public int MasterCategoryQuestionId { get; set; }
        public string CategoryName { get; set; }
        public string Quantity { get; set; }
        public string UserQuestion { get; set; }
    }
}
