//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessCenter.Data
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class MasterCategoryDocument
    {
        [Key]
        public int MasterCategoryDocId { get; set; }
        public string CategoryName { get; set; }
        public string InitialLicense { get; set; }
        public string PostLicensure { get; set; }
        public string Renewal { get; set; }
        public string Agency { get; set; }
        public string Agency_FullName { get; set; }
        public string Div { get; set; }
        public string DivisionFullName { get; set; }
        public string SupportingDocuments { get; set; }
        public string ShortDocName { get; set; }
        public string Description { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<bool> IsPrimaryCategoryDoc { get; set; }
        public Nullable<bool> IsSecondaryLicenseDoc { get; set; }
    }
}
