//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessCenter.Data
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class MasterCategoryPhysicalLocation
    {
        [Key]
        public int RuleId { get; set; }
        public string PrimaryCategory_Id { get; set; }
        public string BusinessMustBeInDC { get; set; }
        public string COFORequired { get; set; }
        public string HOP_EHOPAllowed { get; set; }
        public string ExemptFromAllFees { get; set; }
        public string LicenseType { get; set; }
        public Nullable<bool> Status { get; set; }
    }
}
