//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessCenter.Data
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class MasterBblApplicationStatus
    {
        [Key]
        public int BblApplicationStatusId { get; set; }
        public string Application_Cap_Status { get; set; }
        public string Changed_Cap_Status { get; set; }
    }
}
