//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessCenter.Data
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class MasterPrimaryCategory
    {
        [Key]
        public string PrimaryID { get; set; }
        public string ActivityID { get; set; }
        public string Description { get; set; }
        public string Endorsement { get; set; }
        public string CategoryCode { get; set; }
        public string UnitOne { get; set; }
        public string UnitTwo { get; set; }
        public string App_Type { get; set; }
        public Nullable<bool> IsSecondaryLicenseCategory { get; set; }
        public Nullable<bool> IsSubCategory { get; set; }
        public Nullable<bool> Status { get; set; }

        public Nullable<bool> IsBackgroundInvestigation { get; set; }
        public Nullable<bool> IsPDFShow { get; set; }
    }
}
