//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessCenter.Data
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class OSub_Category_Checklist
    {
        [Key]
        public int OSub_Category { get; set; }
        [Key]
        public string OSub_Description { get; set; }
        public string UnitTwo { get; set; }
    }
}
