//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessCenter.Data
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class OSub_Category_Fees
    {
        [Key]
        public string OSub_Category { get; set; }
        public string OSub_Description { get; set; }
        public string Fee_Code { get; set; }
        public Nullable<int> Start { get; set; }
        public Nullable<int> End { get; set; }
        public Nullable<decimal> License_Fee { get; set; }
        public Nullable<int> Tier { get; set; }
        public string App_Type { get; set; }
        public Nullable<bool> Status { get; set; }
    }
}
