//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessCenter.Data
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class PaymentDetails
    {
        [Key]
        public string PaymentId { get; set; }
        public string MasterId { get; set; }
        public string Ordernumber { get; set; }
        public string PaymentFrom { get; set; }
        public string PaymentMailAddress { get; set; }
        public string Signature { get; set; }
        public Nullable<bool> IsAggree { get; set; }
        public string TranscationId { get; set; }
        public string PaymentStatus { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public string ApproveBy { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<bool> Application_Transcation_Status { get; set; }
    }
}
