//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessCenter.Data
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class SubmissionCorporation_Agent_Address
    {
        [Key]
        public int SCAId { get; set; }
        public Nullable<int> SubCorporationRegId { get; set; }
        public string AddressType { get; set; }
        public string FileNumber { get; set; }
        public string BusinessName { get; set; }
        public string FirstName { get; set; }
        public string MiddelName { get; set; }
        public string LastName { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Address3 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Country { get; set; }
        public string Telephone { get; set; }
        public string ZipCode { get; set; }
        public string Email { get; set; }
        public string Status { get; set; }
        public string Quadrant { get; set; }
        public string UnitNumber { get; set; }
        public string AddressNumber { get; set; }
    }
}
