//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessCenter.Data
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class SubmissionCofo_Hop_Ehop_Address
    {
        [Key]
        public int SubmissionCofo_Hop_Ehop_AddressId { get; set; }
        public int CustomTypeId { get; set; }
        public string CustomType { get; set; }
        public string Name { get; set; }
        public string Street { get; set; }
        public string StreetName { get; set; }
        public string StreetType { get; set; }
        public string Quadrant { get; set; }
        public string UnitType { get; set; }
        public string Unit { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Telephone { get; set; }
        public string Zip { get; set; }
        public Nullable<bool> IsValid { get; set; }
        public string Country { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string AddressID { get; set; }
        public string AddressNumber { get; set; }
        public string AddressNumberSufix { get; set; }
        public string Xcoord { get; set; }
        public string Ycoord { get; set; }
        public string Anc { get; set; }
        public string Ward { get; set; }
        public string Cluster { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public string Vote_Prcnct { get; set; }
        public string Zone { get; set; }
        public string Smd { get; set; }
        public string Ssl { get; set; }
    }
}
