//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessCenter.Data
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class SubmissionCategory
    {
        [Key]
        public int SubmissionCategoryID { get; set; }
        public string MasterId { get; set; }
        public string CategoryTypeID { get; set; }
        public Nullable<decimal> EndorsementFee { get; set; }
        public Nullable<decimal> LicenseCategoryFee { get; set; }
        public string CategoryType { get; set; }
        public string ItemQty { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string Endorsement { get; set; }
    }
}
