//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessCenter.Data
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class SubmissionCorporation_Agent
    {
        [Key]
        public int SubCorporationRegId { get; set; }
        public string MasterId { get; set; }
        public string FileNumber { get; set; }
        public string BusinessName { get; set; }
        public string TradeName { get; set; }
        public string BusinessStructure { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<bool> ChcekedFromCorp { get; set; }
    }
}
