//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessCenter.Data
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class SubmissionLicenseNumberCounter
    {
        [Key]
        public long CounterId { get; set; }
        public Nullable<long> Counter { get; set; }
        public Nullable<int> Sequence { get; set; }
        public Nullable<int> FiscalYear { get; set; }
        public string Type { get; set; }
    }
}
