//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessCenter.Data
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class SubmissiontoAccela
    {
        [Key]
        public long SubmissiontoAccelaId { get; set; }
        public string LicenseNumber { get; set; }
        public Nullable<bool> ApplicationCompleted { get; set; }
        public Nullable<bool> ApplicationCreated { get; set; }
        public Nullable<bool> ApplicationFeeMatched { get; set; }
        public Nullable<bool> RenewalPaymentUpdated { get; set; }
        public Nullable<bool> RenewalFeeMatched { get; set; }
        public Nullable<bool> AllDocumentsUpdated { get; set; }
        public Nullable<bool> EHOPCreated { get; set; }
        public string AccelaGeneratedID { get; set; }
        public Nullable<bool> ProcessCompleted { get; set; }
    }
}
