//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessCenter.Data
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class SubmissionDocument
    {
        [Key]
        public int SubmDocId { get; set; }
        public string MasterId { get; set; }
        public int SubmissionCategoryID { get; set; }
        public string MasterCategoryDocId { get; set; }
        public string SubmittedDocumentType { get; set; }
        public string ApprovedBy { get; set; }
        public string DocRequired { get; set; }
        public string FileName { get; set; }
        public string FileLocation { get; set; }
        public string DocStatus { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
