//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessCenter.Data
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class SubmissionBblAssociationToUsers
    {
        [Key]
        public string SubmissionBblAssociationOtherUid { get; set; }
        public string SubmissionLicense { get; set; }
        public string FromUserId { get; set; }
        public string ToUserId { get; set; }
        public Nullable<System.DateTime> DateOfTransfer { get; set; }
        public string CreatedBy { get; set; }
        public string ReasonForTransfer { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
