//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessCenter.Data
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class UserService
    {
        [Key]
        public int UserListId { get; set; }
        public string DATA_SOURCE { get; set; }
        public Nullable<int> DCBC_ENTITY_ID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string Status { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> updatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string UserId { get; set; }
        public string CompanyName { get; set; }
        public string LicenseNumber { get; set; }
    }
}
