//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessCenter.Data
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class UserBBLService
    {
        [Key]
        public int ServiceID { get; set; }
        public string SubmissionLicense { get; set; }
        public string UserID { get; set; }
        public string Type { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<System.DateTime> LicenseExpirationDate { get; set; }
        public Nullable<bool> Status { get; set; }
        public string CleanHandsType_SSN_FEIN { get; set; }
        public string DCBC_ENTITY_ID { get; set; }
        public string B1_ALT_ID { get; set; }
    }
}
