//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessCenter.Data
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class UserLoginHistory
    {
        [Key]
        public long LoginHisId { get; set; }
        public string UserId { get; set; }
        public Nullable<System.DateTime> LastLoginDate { get; set; }
        public Nullable<int> Count { get; set; }
    }
}
