//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessCenter.Data
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class User
    {
        public User()
        {
            this.UserClaim = new HashSet<UserClaim>();
            this.UserLogin = new HashSet<UserLogin>();
        }
    
        [Key]
        public string Id { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string MobileNumber { get; set; }
        public string PostalCode { get; set; }
        public string State { get; set; }
        public Nullable<System.DateTime> LastLoginDateandTime { get; set; }
        public bool IsActive { get; set; }
        public string Email { get; set; }
        public bool EmailConfirmed { get; set; }
        public string ActivationCode { get; set; }
        public string Password { get; set; }
        public string SecurityStamp { get; set; }
        public string PhoneNumber { get; set; }
        public bool PhoneNumberConfirmed { get; set; }
        public bool TwoFactorEnabled { get; set; }
        public Nullable<System.DateTime> LockoutEndDateUtc { get; set; }
        public bool LockoutEnabled { get; set; }
        public int AccessFailedCount { get; set; }
        public string UserName { get; set; }
        public string SecurityQuestion1 { get; set; }
        public string SecurityQuestion2 { get; set; }
        public string SecurityQuestion3 { get; set; }
        public string SecurityAnswer1 { get; set; }
        public string SecurityAnswer2 { get; set; }
        public string SecurityAnswer3 { get; set; }
        public string Title { get; set; }
        public Nullable<System.DateTime> ActivationDate { get; set; }
        public string SecondaryEmail { get; set; }
        public Nullable<System.DateTime> ChangeEmailValidate { get; set; }
        public Nullable<bool> ChangeEmailConfirmed { get; set; }
        public Nullable<System.DateTime> PreviousEmailValidate { get; set; }
        public Nullable<bool> PreviousEmailConfirmed { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<bool> IsForgot { get; set; }
        public string DeleteComment { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<bool> IsLoggedIn { get; set; }
        public string LoginSessionId { get; set; }
    
        public virtual ICollection<UserClaim> UserClaim { get; set; }
        public virtual ICollection<UserLogin> UserLogin { get; set; }
    }
}
