//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessCenter.Api.PayPalUtility
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public Payment()
        {
            this.EntryPayments = new HashSet<EntryPayment>();
        }
    
        public System.Guid PaymentId { get; set; }
        public string CCType { get; set; }
        public string CCLastFour { get; set; }
        public string CCExpDate { get; set; }
        public string CCFirstName { get; set; }
        public string CCLastName { get; set; }
        public int CCSecurityCode { get; set; }
        public string BillingAddress { get; set; }
        public string BillingCity { get; set; }
        public string BillingState { get; set; }
        public string BillingZip { get; set; }
        public string PayConfirmNumber { get; set; }
        public string PayPalResponse { get; set; }
        public decimal Amount { get; set; }
        public Nullable<System.DateTime> PayReceiptDate { get; set; }
    
        public virtual ICollection<EntryPayment> EntryPayments { get; set; }
    }
}
